export const monsters = [
  {
    "id": "abissal-p2026-0",
    "nome": "ABISSAL",
    "nivel": "2+ (d8)",
    "pv": "8oumais Número: 2-12 (40-400)",
    "numero": "2-12 (40-400)",
    "ca": "16",
    "rm": "1",
    "tamanho": "Médio, Grande (em",
    "jp": "M Inteligência: Mediana a Alta",
    "inteligencia": "Mediana a Alta",
    "movimento": "6 m, 12 m Disposição: Mal/Neutro",
    "disposicao": "Mal/Neutro",
    "sanidade": "1/1d8",
    "clima": "Qualquer",
    "ataques": "Mordida (ID4+1) —",
    "bioma": "Água salgada, Água",
    "xp": "Veja abaixo",
    "tesouros": "s: Tipo 2+",
    "habilidades": "Respiração Aquática, Falar com Peixes,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "abominavel-p2026-0",
    "nome": "ABOMINÁVEL",
    "nivel": "9 (dê)",
    "pv": "45 Número: 1-4",
    "numero": "1-4",
    "ca": "16",
    "rm": "|",
    "tamanho": "Grande",
    "jp": "M Inteligência: Alta",
    "inteligencia": "Alta",
    "movimento": "3 m, 18 m Disposição: Mal/Lei",
    "disposicao": "Mal/Lei",
    "sanidade": "1/2d6",
    "clima": "Tropical, Temperado",
    "ataques": "4 Tentáculos",
    "bioma": "Subterrâneo",
    "xp": "1.600+9",
    "tesouros": "Tipo 8",
    "habilidades": "Escravizar, Habilidades Mágicas, Visgo, Nuvem",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "aguia-gigante-p2026-0",
    "nome": "ÁGUIA GIGANTE",
    "nivel": "4 (dIO)",
    "pv": "24 Número: 1-4",
    "numero": "1-4",
    "ca": "16",
    "rm": "1",
    "tamanho": "Grande",
    "jp": "F Inteligência: Alta",
    "inteligencia": "Alta",
    "movimento": "6m, 30m (voo) Disposição: Neutro/Bem",
    "disposicao": "Neutro/Bem",
    "sanidade": "N/A",
    "clima": "Temperado",
    "ataques": "2 Garras (ID8), —",
    "bioma": "Qualquer terreno",
    "xp": "90+4",
    "tesouros": "Tipo 3",
    "habilidades": "Mergulho, Visão na Penumbra, Visão Aprimorada,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "aiser-p2026-0",
    "nome": "AISER",
    "nivel": "1a4(dB)—",
    "pv": "5a Número: 1-4",
    "numero": "1-4",
    "ca": "18",
    "rm": "|",
    "tamanho": "Pequeno (1,2-1,5m)",
    "jp": "F Inteligência: Baixa a Alta",
    "inteligencia": "Baixa a Alta",
    "movimento": "9m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer plano de fogo",
    "ataques": "Por Arma",
    "bioma": "Plano Elemental do Fogo",
    "xp": "5+1, 10+2,20+3,",
    "tesouros": "Tipo 1 a 4",
    "habilidades": "Aura Flamejante, Imunidade ao Fogo",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "aranha-eterea-p2026-0",
    "nome": "ARANHA ETÉREA",
    "nivel": "5",
    "pv": "25 Número: 1-4",
    "numero": "1-4",
    "ca": "15",
    "rm": "1",
    "tamanho": "Grande",
    "jp": "F Inteligência: Baixa",
    "inteligencia": "Baixa",
    "movimento": "9m, 9m(escalar) Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": ":",
    "clima": "Temperado",
    "ataques": "2 Mordidas (1DIO)",
    "bioma": "Florestas, Subterrâneo",
    "xp": "260+5",
    "tesouros": "Tipo 5",
    "habilidades": "Peçonha, Teia, Mudança, Visão no Escuro, Visão",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "aranha-gigante-p2026-0",
    "nome": "ARANHA GIGANTE",
    "nivel": "Veja",
    "pv": "Veja —— Número: Veja abaixo",
    "numero": "Veja abaixo",
    "ca": null,
    "rm": "1",
    "tamanho": "Veja abaixo",
    "jp": "F Inteligência: Animal a",
    "inteligencia": "Animal a",
    "movimento": "Veja abaixo Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer exceto ártico",
    "ataques": "Veja abaixo",
    "bioma": "Qualquer terreno",
    "xp": "Veja abaixo",
    "tesouros": "Veja abaixo",
    "habilidades": "Tamanho Variável, Peçonha, Teia, Visão na",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "arraia-ixit-p2026-0",
    "nome": "ARRAIA IXIT",
    "nivel": "1 (dê)",
    "pv": "6 Número: 10-100",
    "numero": "10-100",
    "ca": "14",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "M,F Inteligência: Mediana a Alta",
    "inteligencia": "Mediana a Alta",
    "movimento": "9 m (nadar) Disposição: Mal",
    "disposicao": "Mal",
    "sanidade": ":",
    "clima": "Tropical",
    "ataques": "Mordida (3D4)",
    "bioma": "Águas Salgadas",
    "xp": "Veja abaixo",
    "tesouros": "Tipo 5",
    "habilidades": "Habilidades de Clérigo, Vampirismo,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "arvore-do-carrasco-p2026-0",
    "nome": "ÁRVORE DO CARRASCO",
    "nivel": "6",
    "pv": "36 Número: 1",
    "numero": "1",
    "ca": "17/15",
    "rm": "1",
    "tamanho": "Grande (6-9 m)",
    "jp": "F Inteligência: Baixa",
    "inteligencia": "Baixa",
    "movimento": "Nenhum (Veja Disposição: Neutro/Mal",
    "disposicao": "Neutro/Mal",
    "sanidade": "N/A",
    "clima": "Temperado, Tropical",
    "ataques": "Veja abaixo",
    "bioma": "Florestas",
    "xp": "420+6",
    "tesouros": "Nenhum",
    "habilidades": "Ienorar Armadura, Estrangulamento, Ácido,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "atormentado-p2026-0",
    "nome": "ATORMENTADO",
    "nivel": "7 (d12)",
    "pv": "49 Número: 1-6",
    "numero": "1-6",
    "ca": "15",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "M Inteligência: Alta",
    "inteligencia": "Alta",
    "movimento": "9m Disposição: Lei/Mal",
    "disposicao": "Lei/Mal",
    "sanidade": "1/1d6",
    "clima": "Qualquer",
    "ataques": "Toque Incorpóreo (1D8)",
    "bioma": "Qualquer terreno",
    "xp": "720+7",
    "tesouros": "s: Tipo 7",
    "habilidades": "Drenar Energia, Criar Prole, Incorpóreo,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "avia-p2026-0",
    "nome": "ÁVIA",
    "nivel": "1",
    "pv": "6 Número: 1-10",
    "numero": "1-10",
    "ca": "13",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "F Inteligência: Mediana",
    "inteligencia": "Mediana",
    "movimento": "6 m, 27 m (voo) Disposição: Neutro/Bem",
    "disposicao": "Neutro/Bem",
    "sanidade": "N/A",
    "clima": "Alpino (Montanhas)",
    "ataques": "2 Garras (I1D4) ou —",
    "bioma": "Qualquer terreno",
    "xp": "9+1",
    "tesouros": "Tipo 3",
    "habilidades": "Mergulho",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "banshee-p2026-0",
    "nome": "BANSHEE",
    "nivel": "7 (dê)",
    "pv": "35 Número: |",
    "numero": "|",
    "ca": "20",
    "rm": "10",
    "tamanho": "Médio",
    "jp": "M Inteligência: Alta",
    "inteligencia": "Alta",
    "movimento": "9m (voo) Disposição: Mal/Caos",
    "disposicao": "Mal/Caos",
    "sanidade": "1/1d10",
    "clima": "Qualquer",
    "ataques": "Toque Gélido (1D8)",
    "bioma": "Qualquer terreno",
    "xp": "900 +7",
    "tesouros": "s: Tipo 7",
    "habilidades": "Lamento Agourento, Aterrorizante, Incorpórea,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "barghest-p2026-0",
    "nome": "BARGHEST",
    "nivel": "1-9 (dêôj—",
    "pv": "4-36 Número: 1-6",
    "numero": "1-6",
    "ca": "18 (20)",
    "rm": "5",
    "tamanho": "Médio/Grande",
    "jp": "M Inteligência: Alta",
    "inteligencia": "Alta",
    "movimento": "9m, 18m (voo) Disposição: Mal",
    "disposicao": "Mal",
    "sanidade": "0/1d6",
    "clima": "Qualquer",
    "ataques": "Mordida (Veja",
    "bioma": "Os Planos Desolados,",
    "xp": "Veja abaixo",
    "tesouros": "Tipo 8",
    "habilidades": "Habilidades Mágicas, Consumir Almas,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "basilisco-p2026-0",
    "nome": "BASILISCO",
    "nivel": "6",
    "pv": "36 Número: 1-4",
    "numero": "1-4",
    "ca": "16",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "6 m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Árido, Semiárido",
    "ataques": "Mordida (1D10)",
    "bioma": "(Qualquer terreno,",
    "xp": "240+6",
    "tesouros": "Tipo 5",
    "habilidades": "Olhar Petrificante, Visão no Escuro",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "bauk-p2026-0",
    "nome": "BAUK",
    "nivel": "3 (d4)",
    "pv": "9 Número: 1-20",
    "numero": "1-20",
    "ca": "14",
    "rm": "1",
    "tamanho": "Pequeno (1,2m)",
    "jp": "M Inteligência: Mediana",
    "inteligencia": "Mediana",
    "movimento": "18 m Disposição: Caos/Mal",
    "disposicao": "Caos/Mal",
    "sanidade": "N/A",
    "clima": "Qualquer",
    "ataques": "Garra (d6), Mordida",
    "bioma": "Florestas, Subterrâneo",
    "xp": "275+3",
    "tesouros": "Tipo 3",
    "habilidades": "Sensibilidade à Luz, Visão nas Profundezas",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "behemoth-p2026-0",
    "nome": "BEHEMOTH",
    "nivel": "9 (d10)",
    "pv": "54 Número: 1-4",
    "numero": "1-4",
    "ca": "20",
    "rm": "1",
    "tamanho": "Grande",
    "jp": "F Inteligência: Baixa",
    "inteligencia": "Baixa",
    "movimento": "12 m, 4,9 m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer",
    "ataques": "Mordida (2D4),",
    "bioma": "Qualquer terreno,",
    "xp": "2.600 +9",
    "tesouros": "Tipo 9",
    "habilidades": "Arma de Sopro, Não Pode Ser Derrubado,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "berbalang-p2026-0",
    "nome": "BERBALANG",
    "nivel": "2 (dô)",
    "pv": "10 Número: |",
    "numero": "|",
    "ca": "14",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "M Inteligência: Alta",
    "inteligencia": "Alta",
    "movimento": "12m, 18m (voo) Disposição: Caos/Mal",
    "disposicao": "Caos/Mal",
    "sanidade": "1/1d4",
    "clima": "Qualquer",
    "ataques": "2 Garras (1D4),",
    "bioma": "Plano Astral, Qualquer",
    "xp": "32+2",
    "tesouros": "Nenhum",
    "habilidades": "Viagem Planar",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "besouro-bombardeiro-p2026-0",
    "nome": "BESOURO BOMBARDEIRO",
    "nivel": "2 (d8)",
    "pv": "12 Número: 3-12",
    "numero": "3-12",
    "ca": "16",
    "rm": "1",
    "tamanho": "Médio (1,2m de",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "6 m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Temperado",
    "ataques": "Mordida (1D4)",
    "bioma": "Florestas, Pradarias",
    "xp": "120+2",
    "tesouros": "Nenhum",
    "habilidades": "Traços de Besouro, Nuvem Ácida, Faro",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "besouro-cervideo-p2026-0",
    "nome": "BESOURO CERVIDEO",
    "nivel": "7 (dê)",
    "pv": "28 Número: 2-12",
    "numero": "2-12",
    "ca": "17",
    "rm": "1",
    "tamanho": "Grande (3 m de",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "6 m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Temperado, Tropical",
    "ataques": "2 Chifres (1DIO); —",
    "bioma": "Florestas",
    "xp": "975+7",
    "tesouros": "Nenhum",
    "habilidades": "Agarrar, Esmagar, Traços de Besouro, Faro",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "besouro-perfurador-p2026-0",
    "nome": "BESOURO PERFURADOR",
    "nivel": "5 (dê)",
    "pv": "20 Número: 3-18+",
    "numero": "3-18+",
    "ca": "17",
    "rm": "1",
    "tamanho": "Grande (2,7 m de",
    "jp": "F Inteligência: Animal (ver abaixo)",
    "inteligencia": "Animal (ver abaixo)",
    "movimento": "4,5 m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Tropical, Temperado",
    "ataques": "Mordida (5d4) —",
    "bioma": "Florestas",
    "xp": "175+5",
    "tesouros": "Nenhum (Veja abaixo)",
    "habilidades": "Traços de Besouro, Inteligência Coletiva, Faro",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "besouro-de-fogo-p2026-0",
    "nome": "BESOURO DE FOGO",
    "nivel": "1 (dô)",
    "pv": "6 Número: 3-12",
    "numero": "3-12",
    "ca": "16",
    "rm": "1",
    "tamanho": "Pequeno (70 cm)",
    "jp": "N Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "9m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Temperado, Tropical",
    "ataques": "Mordida (2D4)",
    "bioma": "Qualquer terreno",
    "xp": "35+1",
    "tesouros": "Nenhum",
    "habilidades": "Traços de Besouro, Bioluminescência, Faro",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "bico-de-machado-p2026-0",
    "nome": "BICO DE MACHADO",
    "nivel": "3 (dê)",
    "pv": "12 Número: 1-6",
    "numero": "1-6",
    "ca": "14",
    "rm": "1",
    "tamanho": "Grande (2,10 m+)",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "15m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer exceto ártico",
    "ataques": "Bico (2D4), 2",
    "bioma": "Pradarias",
    "xp": "150+3",
    "tesouros": "Nenhum",
    "habilidades": "Visão na Penumbra",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "boglin-p2026-0",
    "nome": "BOGLIN",
    "nivel": "3 (dl10) —",
    "pv": "18 Número: 2-8",
    "numero": "2-8",
    "ca": "15",
    "rm": "1",
    "tamanho": "Pequeno (90 cm)",
    "jp": "F Inteligência: Baixa",
    "inteligencia": "Baixa",
    "movimento": "6 m Disposição: Caos",
    "disposicao": "Caos",
    "sanidade": "N/A",
    "clima": "Qualquer um",
    "ataques": "2 Garras (1D4),",
    "bioma": "Subterrâneo",
    "xp": "60+3",
    "tesouros": "s: Tipo 2",
    "habilidades": "Olfato Aguçado, Secreção Oleosa,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "boolay-p2026-0",
    "nome": "BOOLAY",
    "nivel": "9 (d10) —",
    "pv": "54 Número: |",
    "numero": "|",
    "ca": "22",
    "rm": "1",
    "tamanho": "Grande",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "12m, 3m (escavar) Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Temperado",
    "ataques": "2 Garras (3D6),",
    "bioma": "Qualquer terreno",
    "xp": "900+9",
    "tesouros": "Tipo 8",
    "habilidades": "Visão no Escuro, Visão na Penumbra, Faro, Salto",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "bruxa-repugnante-p2026-0",
    "nome": "BRUXA REPUGNANTE",
    "nivel": "4 (d8)",
    "pv": "20 Número: |",
    "numero": "|",
    "ca": "18",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "M Inteligência: Genial",
    "inteligencia": "Genial",
    "movimento": "6 m Disposição: Mal/Caos",
    "disposicao": "Mal/Caos",
    "sanidade": "N/A",
    "clima": "Qualquer",
    "ataques": "2 Garras (1D4),",
    "bioma": "Qualquer terreno",
    "xp": "110+4",
    "tesouros": "Tipo 5",
    "habilidades": "Guincho, Idiomas, Habilidades Mágicas",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "trasgo-p2026-0",
    "nome": "TRASGO",
    "nivel": "3 (dô)",
    "pv": "15 Número: 6-36",
    "numero": "6-36",
    "ca": "17",
    "rm": "1",
    "tamanho": "Grande",
    "jp": "F Inteligência: Mediana",
    "inteligencia": "Mediana",
    "movimento": "9m Disposição: Caos/Mal",
    "disposicao": "Caos/Mal",
    "sanidade": "N/A",
    "clima": "Qualquer",
    "ataques": "Por Arma",
    "bioma": "Qualquer terreno",
    "xp": "20+3",
    "tesouros": "s: Tipo 2",
    "habilidades": "Visão no Escuro",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "cadaver-enganoso-p2026-0",
    "nome": "CADÁVER ENGANOSO",
    "nivel": "2 (dô)",
    "pv": "10 Número: |",
    "numero": "|",
    "ca": "12",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "F Inteligência: Baixa",
    "inteligencia": "Baixa",
    "movimento": "3 m Disposição: Mal/Neutro",
    "disposicao": "Mal/Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer",
    "ataques": "Mão (1D6) ou Por Arma",
    "bioma": "Qualquer terreno",
    "xp": "25+2",
    "tesouros": "Tipo 3",
    "habilidades": "Ataque de Estrangulamento, Imunidade a",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "o-infernal-p2026-0",
    "nome": "O INFERNAL",
    "nivel": "4 (dô)/8 (d8)",
    "pv": "20/40 Número: 1-6",
    "numero": "1-6",
    "ca": "16",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "F Inteligência: Baixa",
    "inteligencia": "Baixa",
    "movimento": "12 m Disposição: Lei/Mal",
    "disposicao": "Lei/Mal",
    "sanidade": "1/1d8 ou 1/1d10",
    "clima": "Qualquer",
    "ataques": "Mordida",
    "bioma": "Qualquer terreno",
    "xp": "4º",
    "tesouros": "tipo 4/ tipo 8",
    "habilidades": "Arma de Sopro, Mordida Flamejante, Visão no",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "o-teleportador-p2026-0",
    "nome": "O TELEPORTADOR",
    "nivel": "2 (d10)",
    "pv": "12 Número: 4-16",
    "numero": "4-16",
    "ca": "16",
    "rm": "1",
    "tamanho": "Pequeno",
    "jp": "M Inteligência: Mediana",
    "inteligencia": "Mediana",
    "movimento": "9m Disposição: Lei/Bem",
    "disposicao": "Lei/Bem",
    "sanidade": "N/A",
    "clima": "Temperado",
    "ataques": "Mordida (1D6)",
    "bioma": "Pradarias |",
    "xp": "22+2",
    "tesouros": "Tipo 1 i",
    "habilidades": "Piscar, Visão no Escuro, Salto Dimensional, Visão",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "carniceiro-p2026-0",
    "nome": "CARNICEIRO",
    "nivel": "2 (dô)",
    "pv": "10 Número: 1-8, 2-24",
    "numero": "1-8, 2-24",
    "ca": "14",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "F Inteligência: Nenhuma a Mediana",
    "inteligencia": "Nenhuma a Mediana",
    "movimento": "9m Disposição: Mal/Caos",
    "disposicao": "Mal/Caos",
    "sanidade": "1/1d8",
    "clima": "Qualquer",
    "ataques": "2 Garras (1D3), -",
    "bioma": "Qualquer terreno",
    "xp": "20+2",
    "tesouros": "Tipo 1",
    "habilidades": "Paralisia, Visão no Escuro, Traços de Morto-Vivo",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "catoblepas-p2026-0",
    "nome": "CATOBLEPAS",
    "nivel": "6 (dê) —",
    "pv": "24 Número: |",
    "numero": "|",
    "ca": "13",
    "rm": "1",
    "tamanho": "Grande",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "3 m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer",
    "ataques": "Golpe de Cauda (2D4)",
    "bioma": "Água doce",
    "xp": "300+6",
    "tesouros": "N/A",
    "habilidades": "Olhar Mortal, Atordoar",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "cavaleiro-da-morte-p2026-0",
    "nome": "CAVALEIRO DA MORTE",
    "nivel": "9 (d10)",
    "pv": "54  Número:l1",
    "numero": "l1",
    "ca": "20",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "9m Disposição: Mal/Caos",
    "disposicao": "Mal/Caos",
    "sanidade": "1/2d6",
    "clima": "Qualquer",
    "ataques": "Por Arma",
    "bioma": "Qualquer terreno",
    "xp": "2.900+9",
    "tesouros": "Tipo 6",
    "habilidades": "Habilidades Mágicas, Afastar, Sacrifício Final,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "celere-p2026-0",
    "nome": "CÉLERE",
    "nivel": "1 (d12)",
    "pv": "7 Número: 2-8",
    "numero": "2-8",
    "ca": "23",
    "rm": "1",
    "tamanho": "Pequeno",
    "jp": "F Inteligência: Superior",
    "inteligencia": "Superior",
    "movimento": "30m Disposição: Neutro/Mal",
    "disposicao": "Neutro/Mal",
    "sanidade": "N/A",
    "clima": "Temperado",
    "ataques": "2 Por Arma",
    "bioma": "Florestas",
    "xp": "11+1",
    "tesouros": "s: Tipo 4",
    "habilidades": "Bônus de Iniciativa, Ataques Duplos, Habilidades",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "centauro-p2026-0",
    "nome": "CENTAURO",
    "nivel": "4 (d8)",
    "pv": "20 Número: 1,4-24",
    "numero": "1,4-24",
    "ca": "14",
    "rm": "1",
    "tamanho": "Grande",
    "jp": "F Inteligência: Mediana",
    "inteligencia": "Mediana",
    "movimento": "15m Disposição: Neutro/Caos",
    "disposicao": "Neutro/Caos",
    "sanidade": "N/A",
    "clima": "Temperado",
    "ataques": "2 Cascos (1D6), Por",
    "bioma": "Florestas",
    "xp": "80+4",
    "tesouros": "s: Tipo 4",
    "habilidades": "Visão no Escuro, Rastreio 5, Passo Silvestre",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "centelha-espectral-p2026-0",
    "nome": "CENTELHA ESPECTRAL",
    "nivel": "4 (d12)",
    "pv": "28 Número: 1",
    "numero": "1",
    "ca": "15",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "M Inteligência: Mediana",
    "inteligencia": "Mediana",
    "movimento": "9m (voo) Disposição: Mal/Neutro",
    "disposicao": "Mal/Neutro",
    "sanidade": "1/1d8",
    "clima": "Qualquer",
    "ataques": "Toque (drenar habilidade) —",
    "bioma": "Qualquer terreno",
    "xp": "160+4",
    "tesouros": "Tipo 5",
    "habilidades": "Balbuciar, Incorpóreo, Loucura, Drenar",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "centopeia-gigante-p2026-0",
    "nome": "CENTOPEIA GIGANTE",
    "nivel": "3 (d8)",
    "pv": "15 Número: 1-4",
    "numero": "1-4",
    "ca": "15",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "18 m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer exceto ártico",
    "ataques": "Mordida (1D4)",
    "bioma": null,
    "xp": "45+3",
    "tesouros": "N/A",
    "habilidades": "Paralisia, Peçonha",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "chacal-humanoide-p2026-0",
    "nome": "CHACAL HUMANOIDE",
    "nivel": "4 (d8)",
    "pv": "20 Número: 1-4",
    "numero": "1-4",
    "ca": "16",
    "rm": "1",
    "tamanho": "Médio",
    "jp": "F Inteligência: Mediana a Alta",
    "inteligencia": "Mediana a Alta",
    "movimento": "9m Disposição: Caos/Mal",
    "disposicao": "Caos/Mal",
    "sanidade": "N/A",
    "clima": "Árido, Semiárido,",
    "ataques": "Mordida (2D4) ou Por",
    "bioma": "Florestas, Desertos",
    "xp": "270+4",
    "tesouros": "s: Tipo 4",
    "habilidades": "Transformação, Imunidade a Armas (+1),",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "cocatriz-p2026-0",
    "nome": "COCATRIZ",
    "nivel": "5 (dI0)",
    "pv": "30 Número: 1-6",
    "numero": "1-6",
    "ca": "14",
    "rm": "1",
    "tamanho": "Pequeno",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "6m, 18m(voo) Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer exceto ártico",
    "ataques": "Mordida (1D3)",
    "bioma": "Qualquer terreno",
    "xp": "160+5",
    "tesouros": "Tipo 5",
    "habilidades": "Petrificação, Visão no Escuro, Visão na",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "corvideo-atroz-p2026-0",
    "nome": "CORVÍDEO ATROZ",
    "nivel": "2 (dê)",
    "pv": "10 Número: 1-6",
    "numero": "1-6",
    "ca": "18",
    "rm": "1",
    "tamanho": "Grande (2,40m)",
    "jp": "F Inteligência: Baixa a Mediana",
    "inteligencia": "Baixa a Mediana",
    "movimento": "Disposição: Caos/Mal",
    "disposicao": "Caos/Mal",
    "sanidade": ":",
    "clima": "Qualquer",
    "ataques": "2 Garras (1D4),",
    "bioma": "Subterrâneo",
    "xp": "20+2",
    "tesouros": "Tipo 3",
    "habilidades": "Grasnido",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "couatl-p2026-0",
    "nome": "COUATL",
    "nivel": "9 (dê)",
    "pv": "45 Número: |",
    "numero": "|",
    "ca": "21",
    "rm": "1",
    "tamanho": "Grande",
    "jp": "MF Inteligência: Superior",
    "inteligencia": "Superior",
    "movimento": "6m, 18mí(voo) Disposição: Bem/Lei",
    "disposicao": "Bem/Lei",
    "sanidade": "N/A",
    "clima": "Tropical",
    "ataques": "Mordida (1D3),",
    "bioma": "Florestas",
    "xp": "1.800+9",
    "tesouros": "Tipo 8",
    "habilidades": "Constringir, Peçonha, Habilidades Mágicas,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "demilich-p2026-0",
    "nome": "DEMILICH",
    "nivel": "10(dd)",
    "pv": "50 — —Númeror1l",
    "numero": "r1l",
    "ca": "20",
    "rm": "10",
    "tamanho": "Médio",
    "jp": "M, F Inteligência: Supra-Genial",
    "inteligencia": "Supra-Genial",
    "movimento": "Om, 6m Disposição: Mal/Neutro",
    "disposicao": "Mal/Neutro",
    "sanidade": "0/1d4 (Veja abaixo)",
    "clima": "Qualquer",
    "ataques": "Toque (1D4), Veja",
    "bioma": "Qualquer terreno",
    "xp": "4.500+10",
    "tesouros": "Tipo 9",
    "habilidades": "Dreno de Energia, Ressurgir, Resistência a",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "demonete-da-fumaca-p2026-0",
    "nome": "DEMONETE DA FUMAÇA",
    "nivel": "2 (dô)",
    "pv": "10 Número: 1-3",
    "numero": "1-3",
    "ca": "15",
    "rm": "1",
    "tamanho": "Pequeno",
    "jp": "F Inteligência: Mediana",
    "inteligencia": "Mediana",
    "movimento": "12 m, 12 m (voo) Disposição: Mal",
    "disposicao": "Mal",
    "sanidade": "N/A",
    "clima": "Qualquer Ar",
    "ataques": "2 Garras (1d3)",
    "bioma": "Plano Elemental do Ar",
    "xp": "15+2",
    "tesouros": "Nenhum",
    "habilidades": "Ataque Elemental",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "demonete-da-neblina-p2026-0",
    "nome": "DEMONETE DA NEBLINA",
    "nivel": "2 (d10)",
    "pv": "12 Número: 1-3",
    "numero": "1-3",
    "ca": "14",
    "rm": "1",
    "tamanho": "Pequeno",
    "jp": "F Inteligência: Mediana",
    "inteligencia": "Mediana",
    "movimento": "9 m, 12 m (voo) Disposição: Mal",
    "disposicao": "Mal",
    "sanidade": "N/A",
    "clima": "Qualquer Neblina",
    "ataques": "2 Garras (1d3)",
    "bioma": "Plano Elemental do Ar",
    "xp": "15+2",
    "tesouros": "Nenhum",
    "habilidades": "Ataque Elemental",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "demonete-do-fogo-p2026-0",
    "nome": "DEMONETE DO FOGO",
    "nivel": "2 (d10)",
    "pv": "12 Número: 1-3",
    "numero": "1-3",
    "ca": "14",
    "rm": "1",
    "tamanho": "Pequeno",
    "jp": "F Inteligência: Mediana",
    "inteligencia": "Mediana",
    "movimento": "9 m, 12 m (voo) — Disposição: Mal",
    "disposicao": "Mal",
    "sanidade": "N/A",
    "clima": "Qualquer Fogo",
    "ataques": "2 Garras (1d3)",
    "bioma": "Plano Elemental do",
    "xp": "15+2",
    "tesouros": "Nenhum",
    "habilidades": "Ataque Elemental",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "demonete-do-magma-p2026-0",
    "nome": "DEMONETE DO MAGMA",
    "nivel": "2",
    "pv": "14 Número: 1-3",
    "numero": "1-3",
    "ca": "14",
    "rm": "1",
    "tamanho": "Pequeno",
    "jp": "F Inteligência: Mediana",
    "inteligencia": "Mediana",
    "movimento": "6 m, 9 m (voo) Disposição: Mal",
    "disposicao": "Mal",
    "sanidade": ":",
    "clima": "Qualquer Magma",
    "ataques": "2 Garras (1d3)",
    "bioma": "Plano Elemental do",
    "xp": "17+2",
    "tesouros": "Nenhum",
    "habilidades": "Ataque Elemental",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "nio-bel-p2026-0",
    "nome": "NIO BEL",
    "nivel": "7 (dê)",
    "pv": "35 Número: 1-6",
    "numero": "1-6",
    "ca": "22",
    "rm": "4",
    "tamanho": "Grande",
    "jp": "F Inteligência: Baixa",
    "inteligencia": "Baixa",
    "movimento": "9 m, 15 m (voo) Disposição: Neutro/Mal",
    "disposicao": "Neutro/Mal",
    "sanidade": "1/1d8",
    "clima": "Qualquer um com",
    "ataques": "2 Asas (2D4), 2",
    "bioma": "Plano Elemental do Ar",
    "xp": "7120+7",
    "tesouros": "s: Tipo 7",
    "habilidades": "Ataque de Fumaça, Visão no Escuro, Forma de",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "nio-gritador-p2026-0",
    "nome": "NIO GRITADOR",
    "nivel": "3 (dô)",
    "pv": "15 Número: |",
    "numero": "|",
    "ca": "18",
    "rm": "1",
    "tamanho": "Pequeno",
    "jp": "F Inteligência: Baixa",
    "inteligencia": "Baixa",
    "movimento": "9m, 9m (voo) Disposição: Mal/Lei",
    "disposicao": "Mal/Lei",
    "sanidade": "N/A",
    "clima": "Qualquer",
    "ataques": "Cauda (1D6)",
    "bioma": "Planos Desolados,",
    "xp": "35+3",
    "tesouros": "s: Tipo 2",
    "habilidades": "Grito",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "dermaptero-p2026-0",
    "nome": "DERMÁPTERO",
    "nivel": "1 (d2)",
    "pv": "1 Número: 20+120",
    "numero": "20+120",
    "ca": "10",
    "rm": "1",
    "tamanho": "Pequeno (7-15 cm.)",
    "jp": "F Inteligência: Nenhuma",
    "inteligencia": "Nenhuma",
    "movimento": "Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Tropical, Temperado",
    "ataques": "N/A",
    "bioma": "Florestas, Subterrâneo",
    "xp": "10+1",
    "tesouros": "Nenhum",
    "habilidades": "Pôr Ovos",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "desencantador-p2026-0",
    "nome": "DESENCANTADOR",
    "nivel": "5 (dô8)",
    "pv": "25 Número: l1",
    "numero": "l1",
    "ca": "15",
    "rm": "1",
    "tamanho": "Médio (1,2m na",
    "jp": "F Inteligência: Mediana",
    "inteligencia": "Mediana",
    "movimento": "9m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer",
    "ataques": "Chute (1D10)",
    "bioma": "Qualquer terreno",
    "xp": "200+5",
    "tesouros": "N/A",
    "habilidades": "Detectar Magia, Drenar Magia",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "devorador-de-intelecto-p2026-0",
    "nome": "DEVORADOR DE INTELECTO",
    "nivel": "6 (d4)",
    "pv": "12. Número: 1-2",
    "numero": "1-2",
    "ca": "16",
    "rm": "1",
    "tamanho": "Pequeno (16,5",
    "jp": "M Inteligência: Alta",
    "inteligencia": "Alta",
    "movimento": "12 m Disposição: Mal",
    "disposicao": "Mal",
    "sanidade": "1/1d8",
    "clima": "Qualquer",
    "ataques": "4 Garras (1d4) terreno (especialmente",
    "bioma": "Qualquer",
    "xp": "600+6",
    "tesouros": "Nenhum",
    "habilidades": "Sentir Intelecto, Telepatia, Consumir",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "diabrete-p2026-0",
    "nome": "DIABRETE",
    "nivel": "1 (dô)",
    "pv": "5 Número: |",
    "numero": "|",
    "ca": "15",
    "rm": "3",
    "tamanho": "Pequeno",
    "jp": "M Inteligência: Alta",
    "inteligencia": "Alta",
    "movimento": "6m, 18m(voo) — Disposição: Mal/Lei",
    "disposicao": "Mal/Lei",
    "sanidade": "1/1d4",
    "clima": "Qualquer",
    "ataques": "Mordida (1d4),",
    "bioma": "Qualquer terreno",
    "xp": "19+1",
    "tesouros": "Tipo 1",
    "habilidades": "Invisibilidade, Peçonha, Imunidade a Armas",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "anquilossauro-p2026-0",
    "nome": "ANQUILOSSAURO",
    "nivel": "9 (d10)",
    "pv": "45 Número: 2-5",
    "numero": "2-5",
    "ca": "; 20 RM de comprmento)",
    "rm": "de comprmento)",
    "tamanho": null,
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "4,5 m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Tropical",
    "ataques": "Cauda de Clava (3D8) —",
    "bioma": "Florestas, Pradarias",
    "xp": "1.000+9",
    "tesouros": "Nenhum",
    "habilidades": "Pisotear, Visão na Penumbra",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "deinonico-p2026-0",
    "nome": "DEINONICO",
    "nivel": "4 (d8)",
    "pv": "16 Número: 1-6",
    "numero": "1-6",
    "ca": "16",
    "rm": "1",
    "tamanho": "Grande (3 m de",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "18 m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Tropical, Árido",
    "ataques": "2 Garras (1D3),",
    "bioma": "Florestas, Pradarias",
    "xp": "270+4",
    "tesouros": "Nenhum",
    "habilidades": "Saltar, Dilacerar",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "estegossauro-p2026-0",
    "nome": "ESTEGOSSAURO",
    "nivel": "18 (d10)",
    "pv": "90 Número: 2-8",
    "numero": "2-8",
    "ca": "18/15",
    "rm": "1 comprimento, 2,5 m + de",
    "tamanho": "Grande (7,8 m de",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": null,
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Tropical",
    "ataques": "Cauda (5D8)",
    "bioma": "Florestas, Pradarias",
    "xp": "5.800+18",
    "tesouros": "Nenhum",
    "habilidades": "Pisotear, Visão na Penumbra",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "mosassauro-p2026-0",
    "nome": "MOSASSAURO",
    "nivel": "12 (d10)",
    "pv": "80 Número: 1-3",
    "numero": "1-3",
    "ca": "13",
    "rm": "1",
    "tamanho": "Grande (15 m de",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "15m, 12m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer",
    "ataques": "Mordida (4D8)",
    "bioma": "Agua doce, Agua",
    "xp": "4.000+12",
    "tesouros": "Nenhum",
    "habilidades": "Prender a Respiração",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "plesiossauro-p2026-0",
    "nome": "PLESIOSSAURO",
    "nivel": "20 (d10)",
    "pv": "100 Número: 1-3",
    "numero": "1-3",
    "ca": "so Mao",
    "rm": null,
    "tamanho": null,
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "12 m (natação) Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer",
    "ataques": "Mordida (5D8) .. Agua doce, Agua",
    "bioma": null,
    "xp": "8.000+20",
    "tesouros": "Nenhum",
    "habilidades": "Prender a Respiração",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "pterossauro-p2026-0",
    "nome": "PTEROSSAURO",
    "nivel": "6 (d10)",
    "pv": "40 Número: 1-8",
    "numero": "1-8",
    "ca": "15",
    "rm": "1 ANNAN (15 m de",
    "tamanho": null,
    "jp": "F Disposição: Neutro",
    "inteligencia": null,
    "movimento": "3m, 9m (voo) Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer exceto ártico",
    "ataques": "Mordida (3D4)",
    "bioma": "Qualquer terreno",
    "xp": "210+6",
    "tesouros": "Nenhum",
    "habilidades": "Mergulho, Surpresa",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "pteranodonte-p2026-0",
    "nome": "PTERANODONTE",
    "nivel": "3 (dô)",
    "pv": "21 Número: 3-18",
    "numero": "3-18",
    "ca": "13",
    "rm": "1 NANA (9 m de",
    "tamanho": null,
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "3m, 12m (voo) Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer exceto",
    "ataques": "Mordida (2D4)",
    "bioma": "Qualquer terreno",
    "xp": "115+3",
    "tesouros": "Nenhum",
    "habilidades": "Visão na Penumbra",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "tiranossauro-p2026-0",
    "nome": "TIRANOSSAURO",
    "nivel": "18 (d8)",
    "pv": "90 Número: 1-4",
    "numero": "1-4",
    "ca": "15",
    "rm": "1",
    "tamanho": "Grande (15 m de",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "12 m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer exceto ártico",
    "ataques": "Mordida (5D8)",
    "bioma": "Qualquer terreno",
    "xp": "7.900+18",
    "tesouros": "s: Tipo 10",
    "habilidades": "Engolir Inteiro, Faro, Visão na Penumbra",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "triceratops-p2026-0",
    "nome": "TRICERÁTOPS",
    "nivel": "16 (d8)",
    "pv": "80 Número: 1-10",
    "numero": "1-10",
    "ca": "18",
    "rm": "1",
    "tamanho": "Grande (7,5 m' +",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "9m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Qualquer exceto",
    "ataques": "3 Chifres (1D12)",
    "bioma": "Qualquer terreno",
    "xp": "6.100+16",
    "tesouros": "Tipo 9",
    "habilidades": "Investida Poderosa, Pisotear, Visão na",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "dragonete-de-fogo-p2026-0",
    "nome": "DRAGONETE DE FOGO",
    "nivel": "3 (dê)",
    "pv": "15 Número: 1-2",
    "numero": "1-2",
    "ca": "15",
    "rm": "1",
    "tamanho": "Pequeno",
    "jp": "F Inteligência: Animal",
    "inteligencia": "Animal",
    "movimento": "6 m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Temperado",
    "ataques": "Mordida (1D8)",
    "bioma": "Qualquer terreno",
    "xp": "30+3",
    "tesouros": "Nenhum",
    "habilidades": "Arma de Sopro",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "o-azul-p2026-0",
    "nome": "O AZUL",
    "nivel": "Especial.",
    "pv": "Especial Número: 1-3",
    "numero": "1-3",
    "ca": "Especial",
    "rm": "Especial!",
    "tamanho": "Especial (Veja",
    "jp": "MF Inteligência: Ver Tabela",
    "inteligencia": "Ver Tabela",
    "movimento": "12 m, 45 m Disposição: Mal/Lei",
    "disposicao": "Mal/Lei",
    "sanidade": "Por Idade",
    "clima": "Árido, Semiárido",
    "ataques": "2 Garras (1D6), Asa —",
    "bioma": "Deserto",
    "xp": "Veja abaixo",
    "tesouros": "Ver Tabela (coleção)",
    "habilidades": "Arma de Sopro, Magia de Dragão, Habilidades",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "o-branco-p2026-0",
    "nome": "O BRANCO",
    "nivel": ":",
    "pv": "Especial\" Número: 1-6",
    "numero": "1-6",
    "ca": "Especial",
    "rm": "Especial.",
    "tamanho": "Especial (Veja",
    "jp": "M, F Inteligência: Ver Tabela",
    "inteligencia": "Ver Tabela",
    "movimento": "18m, 60m Disposição: Mal/Caos",
    "disposicao": "Mal/Caos",
    "sanidade": "Por Idade",
    "clima": "Ártico",
    "ataques": "2 Garras (1D4),",
    "bioma": "Qualquer terreno,",
    "xp": "Veja abaixo",
    "tesouros": "Ver Tabela (coleção)",
    "habilidades": "Arma de Sopro, Magia de Dragão, Habilidades Mágicas,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "o-de-bronze-p2026-0",
    "nome": "O DE BRONZE",
    "nivel": "Especial.",
    "pv": "Especial , |",
    "numero": "1-6",
    "ca": "Especial!",
    "rm": "Especial —",
    "tamanho": "Especial (Veja",
    "jp": "M, F Inteligência: Ver Tabela",
    "inteligencia": "Ver Tabela",
    "movimento": "12 m, 45 m (voo), : o. |",
    "disposicao": "Bem/Lei",
    "sanidade": "Por Idade",
    "clima": "Temperado, Tropical",
    "ataques": "2 Garras (2DD), Asa o P",
    "bioma": "Qualquer 96U",
    "xp": "Veja abaixo",
    "tesouros": "Ver Tabela",
    "habilidades": "Arma de Sopro, Magia de Dragão, Habilidades",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "o-de-cobre-p2026-0",
    "nome": "O DE COBRE",
    "nivel": ":",
    "pv": "Especial Número: 1-4",
    "numero": "1-4",
    "ca": "Especial.",
    "rm": "Especial",
    "tamanho": "Especial (Veja",
    "jp": "M, F Inteligência: Ver Tabela",
    "inteligencia": "Ver Tabela",
    "movimento": "12 m, 45 m (voo) Disposição: Bem/Caos",
    "disposicao": "Bem/Caos",
    "sanidade": "Por Idade",
    "clima": "Árido, Temperado,",
    "ataques": "2 Garras (1D4), -—",
    "bioma": "Qualquer terreno",
    "xp": "Veja abaixo",
    "tesouros": "Ver Tabela (coleção)",
    "habilidades": "Arma de Sopro, Magia de Dragão, Habilidades",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "dragao-de-ouro-p2026-0",
    "nome": "DRAGAO DE OURO",
    "nivel": "Especial",
    "pv": "Especial!\" Número: 1",
    "numero": "1",
    "ca": "Especial",
    "rm": "Especial",
    "tamanho": "Especial (Veja",
    "jp": "M, F Inteligência: Ver Tabela",
    "inteligencia": "Ver Tabela",
    "movimento": "18 m, 60 m (voo), Ilêê Disposição: Bem/Lei",
    "disposicao": "Bem/Lei",
    "sanidade": "Por Idade",
    "clima": "Qualquer",
    "ataques": "2 Garras (118), Asa (1D8),",
    "bioma": "Qualquer terreno",
    "xp": "Veja abaixo",
    "tesouros": "Ver Tabela (coleção)",
    "habilidades": "Arma de Sopro, Magia de Dragão, Habilidades",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "o-de-platina-p2026-0",
    "nome": "O DE PLATINA",
    "nivel": "Especial",
    "pv": ":",
    "numero": "1",
    "ca": "Especial!*—",
    "rm": "Especial.",
    "tamanho": "Especial",
    "jp": "M, F Inteligência: Ver Tabela",
    "inteligencia": "Ver Tabela",
    "movimento": "18 m, 45 m Disposição: Bem",
    "disposicao": "Bem",
    "sanidade": "Por Idade",
    "clima": "Qualquer",
    "ataques": "2 Garras (2D6),",
    "bioma": "Qualquer terreno",
    "xp": "Veja abaixo",
    "tesouros": "Ver Tabela (coleção)",
    "habilidades": "Arma de Sopro, Magia de Dragão, Habilidades",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "dragao-de-prata-p2026-0",
    "nome": "DRAGAO DE PRATA",
    "nivel": "Especial.",
    "pv": "Especial Número: 1-2",
    "numero": "1-2",
    "ca": "Especial",
    "rm": "Especial!",
    "tamanho": "Especial (Veja",
    "jp": "MF Inteligência: Ver Tabela",
    "inteligencia": "Ver Tabela",
    "movimento": "12 m, 45 m (voo) Disposição: Bem/Lei",
    "disposicao": "Bem/Lei",
    "sanidade": "Por Idade",
    "clima": "Tropical, Temperado,",
    "ataques": "2 Garras (1D6),",
    "bioma": "Qualquer terra,",
    "xp": "Veja abaixo",
    "tesouros": "Ver Tabela (coleção)",
    "habilidades": "Arma de Sopro, Magia de Dragão, Habilidades",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "dragao-lich-p2026-0",
    "nome": "DRAGAO LICH",
    "nivel": "por tipo de",
    "pv": "por tipo de Número: |",
    "numero": "|",
    "ca": "por tipo de drtragãoo—",
    "rm": "16",
    "tamanho": "por tipo",
    "jp": "M, F Inteligência: por",
    "inteligencia": "por",
    "movimento": "por tipo de dragão Disposição: Mal",
    "disposicao": "Mal",
    "sanidade": "2/2d6",
    "clima": "por tipo de",
    "ataques": "por tipo de dragão e idade +",
    "bioma": "por tipo de",
    "xp": "por tipo de dragão e idade +1.000",
    "tesouros": "por tipo de",
    "habilidades": "Poderoso, Traços de Dragão, Feitiços,",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "o-negro-p2026-0",
    "nome": "O NEGRO",
    "nivel": "Especial.",
    "pv": "Especial Número: 1-4",
    "numero": "1-4",
    "ca": "Especial!",
    "rm": "Especial.",
    "tamanho": "Especial (Veja",
    "jp": "M, F Inteligência: Ver Tabela",
    "inteligencia": "Ver Tabela",
    "movimento": "18m, 49m (voo), — Disposição: Mal/Caos",
    "disposicao": "Mal/Caos",
    "sanidade": "Por Idade",
    "clima": "Qualquer",
    "ataques": "2 Garras (ID4), Asa",
    "bioma": "Água doce",
    "xp": "Veja abaixo",
    "tesouros": "Ver Tabela (coleção)",
    "habilidades": "Arma de Sopro, Magia de Dragão, Habilidades",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "dragao-verde-p2026-0",
    "nome": "DRAGAO VERDE",
    "nivel": "Especial.",
    "pv": "Especial Número: 1-4",
    "numero": "1-4",
    "ca": "Especial",
    "rm": "Especial",
    "tamanho": "Especial (Veja",
    "jp": "M, F Inteligência: Ver Tabela",
    "inteligencia": "Ver Tabela",
    "movimento": "12 m, 45 m (voo), 12º Disposição: Mal/Lei",
    "disposicao": "Mal/Lei",
    "sanidade": "Por Idade",
    "clima": "Temperado",
    "ataques": "2 Garras (1D4), Asa",
    "bioma": "Florestas,",
    "xp": "Veja abaixo",
    "tesouros": "Ver Tabela",
    "habilidades": "Arma de Sopro, Magia de Dragão, Habilidades",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "ao-vermelho-p2026-0",
    "nome": "AO VERMELHO",
    "nivel": "Especial",
    "pv": "Especial! Número: 1",
    "numero": "1",
    "ca": "Especial",
    "rm": "Especial.",
    "tamanho": "Especial (Veja",
    "jp": "M, F Inteligência: Ver Tabela",
    "inteligencia": "Ver Tabela",
    "movimento": "12 m, 45 m (voo) Disposição: Mal/Caos",
    "disposicao": "Mal/Caos",
    "sanidade": "Por Idade",
    "clima": "Temperado, Tropical",
    "ataques": "2 Garras (1D8),",
    "bioma": "Qualquer terreno",
    "xp": "Veja abaixo",
    "tesouros": "Ver Tabela",
    "habilidades": "Arma de Sopro, Magia de Dragão, Habilidades",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "driade-p2026-0",
    "nome": "DRÍADE",
    "nivel": "2 (dê) —",
    "pv": "10 Número: |",
    "numero": "|",
    "ca": "17",
    "rm": "10",
    "tamanho": "Médio",
    "jp": "M Inteligência: Alta",
    "inteligencia": "Alta",
    "movimento": "9m Disposição: Neutro",
    "disposicao": "Neutro",
    "sanidade": "N/A",
    "clima": "Temperado",
    "ataques": "Adaga (1D4)",
    "bioma": "Florestas",
    "xp": "39+2",
    "tesouros": "Tipo 1",
    "habilidades": "Habilidades Mágicas, Passo das Árvore, Empatia",
    "pag": "2026",
    "bloco": 1
  },
  {
    "id": "dvergar-p2026-0",
    "nome": "DVERGAR",
    "nivel": "1 (dI10)",
    "pv": "6 Número: 2-8, 10-40",
    "numero": "2-8, 10-40",
    "ca": "lóouPor",
    "rm": "1",
    "tamanho": "Pequeno (1,2m)",
    "jp": "F Inteligência: Mediana a Alta",
    "inteligencia": "Mediana a Alta",
    "movimento": "Disposição: Mal/Caos",
    "disposicao": "Mal/Caos",
    "sanidade": "N/A",
    "clima": "Qualquer",
    "ataques": "Por Arma",
    "bioma": "Subterrâneo",
    "xp": "7+1",
    "tesouros": "Tipo 3",
    "habilidades": "Habilidades Mágicas, Sensibilidade à Luz,",
    "pag": "2026",
    "bloco": 1
  }
]