export const items = [
  {
    "id": "ID-2-20260102211820",
    "type": "alojamento",
    "name": "Estalagem comum",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-3-20260102211820",
    "type": "alojamento",
    "name": "Estalagem Boa",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-4-20260102211820",
    "type": "alojamento",
    "name": "Estalagem Pobre",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-5-20260102211820",
    "type": "alojamento",
    "name": "Sala comunal (apenas o andar)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-6-20260102211820",
    "type": "alojamento",
    "name": "Comum (piso de palha)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-7-20260102211820",
    "type": "alojamento",
    "name": "1 cama sem mobiliário",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-8-20260102211820",
    "type": "alojamento",
    "name": "2 camas sem mobiliário",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-9-20260102211820",
    "type": "alojamento",
    "name": "4 camas sem mobiliário",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-10-20260102211820",
    "type": "alojamento",
    "name": "5+ Camas sem mobiliário (+15 PP por cama extra)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-11-20260102211820",
    "type": "alojamento",
    "name": "1 Cama mobiliada",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-12-20260102211820",
    "type": "alojamento",
    "name": "2 Camas mobiliadas",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-13-20260102211820",
    "type": "alojamento",
    "name": "4 Camas mobiliadas",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-14-20260102211820",
    "type": "alojamento",
    "name": "5+ Camas mobiliadas (+1 PO por cama extra)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-15-20260102211820",
    "type": "alojamento",
    "name": "Suíte sem mobília",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-16-20260102211820",
    "type": "alojamento",
    "name": "Suíte mobiliada",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-17-20260102211820",
    "type": "arma",
    "name": "Adaga",
    "effect": "dano 1d4",
    "gold": 2,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-18-20260102211820",
    "type": "arma",
    "name": "Alabarda",
    "effect": "dano 1d10",
    "gold": 10,
    "ev": 5,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-19-20260102211820",
    "type": "arma",
    "name": "Cestus",
    "effect": "dano +1",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-20-20260102211820",
    "type": "arma",
    "name": "Cutelo",
    "effect": "dano 1d4",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-21-20260102211820",
    "type": "arma",
    "name": "Espada Bastarda",
    "effect": "dano 1d10",
    "gold": 25,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-22-20260102211820",
    "type": "arma",
    "name": "Espada Broadsword",
    "effect": "dano 2d4",
    "gold": 12,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-23-20260102211820",
    "type": "arma",
    "name": "Espada Cimitarra",
    "effect": "dano 1d6",
    "gold": 15,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-24-20260102211820",
    "type": "arma",
    "name": "Espada Curta",
    "effect": "dano 1d6",
    "gold": 10,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-25-20260102211820",
    "type": "arma",
    "name": "Espada de Gancho",
    "effect": "dano 1d4+1",
    "gold": 25,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "ilusionista",
      "mago",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-26-20260102211820",
    "type": "arma",
    "name": "Espada Longa",
    "effect": "dano 1d8",
    "gold": 15,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-27-20260102211820",
    "type": "arma",
    "name": "Espada Rapieira",
    "effect": "dano 1d6",
    "gold": 20,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-28-20260102211820",
    "type": "arma",
    "name": "Foice de Guerra",
    "effect": "dano 2d4",
    "gold": 18,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-29-20260102211820",
    "type": "arma",
    "name": "Garfo Fauchard",
    "effect": "dano 1d8",
    "gold": 15,
    "ev": 5,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-30-20260102211820",
    "type": "arma",
    "name": "Garfo militar",
    "effect": "dano 1d8",
    "gold": 10,
    "ev": 5,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-31-20260102211820",
    "type": "arma",
    "name": "Gato de nove caudas",
    "effect": "dano 1d3",
    "gold": 9,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-32-20260102211820",
    "type": "arma",
    "name": "Lança Partisan",
    "effect": "dano 1d8",
    "gold": 10,
    "ev": 5,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-33-20260102211820",
    "type": "arma",
    "name": "Lança Pesada",
    "effect": "dano 1d8",
    "gold": 10,
    "ev": 7,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-34-20260102211820",
    "type": "arma",
    "name": "Maça Pesada",
    "effect": "dano 1d8",
    "gold": 12,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-35-20260102211820",
    "type": "arma",
    "name": "Machado Barbado",
    "effect": "dano 3d4",
    "gold": 20,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-36-20260102211820",
    "type": "arma",
    "name": "Machado Bardiche",
    "effect": "dano 2d4",
    "gold": 15,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-37-20260102211820",
    "type": "arma",
    "name": "Machado de arremesso",
    "effect": "dano 1d6",
    "gold": 4,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-38-20260102211820",
    "type": "arma",
    "name": "Machado de Batalha",
    "effect": "dano 1d8",
    "gold": 10,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-39-20260102211820",
    "type": "arma",
    "name": "Machado de duas mãos",
    "effect": "dano 1d12",
    "gold": 20,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-40-20260102211820",
    "type": "arma",
    "name": "Machado, perfurador",
    "effect": "dano 1d8+1",
    "gold": 17,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-41-20260102211820",
    "type": "arma",
    "name": "Mangual Leve",
    "effect": "dano 1d8",
    "gold": 8,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-42-20260102211820",
    "type": "arma",
    "name": "Mangual Pesado",
    "effect": "dano 1d10",
    "gold": 15,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-43-20260102211820",
    "type": "arma",
    "name": "Marreta",
    "effect": "dano 1d10",
    "gold": 12,
    "ev": 5,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-44-20260102211820",
    "type": "arma",
    "name": "Morningstar",
    "effect": "dano 2d4",
    "gold": 8,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-45-20260102211820",
    "type": "arma",
    "name": "Picareta bico de corvo",
    "effect": "dano 1d6",
    "gold": 15,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-46-20260102211820",
    "type": "arma",
    "name": "Podão ou gancho",
    "effect": "dano 2d4",
    "gold": 12,
    "ev": 5,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-47-20260102211820",
    "type": "arma",
    "name": "Punhos de bronze",
    "effect": "dano 1d3",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-48-20260102211820",
    "type": "arma",
    "name": "Tridente",
    "effect": "dano 1d8",
    "gold": 10,
    "ev": 5,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-49-20260102211820",
    "type": "arma",
    "name": "Cajado",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-50-20260102211820",
    "type": "arma",
    "name": "Chicote",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-51-20260102211820",
    "type": "arma",
    "name": "Clava",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-52-20260102211820",
    "type": "arma",
    "name": "Clava pesada",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-53-20260102211820",
    "type": "arma",
    "name": "Cutelo longo",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-54-20260102211820",
    "type": "arma",
    "name": "Espada larga, 9 anéis",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-55-20260102211820",
    "type": "arma",
    "name": "Espada Cimitarra grande",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-56-20260102211820",
    "type": "arma",
    "name": "Espada de duas mãos",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-57-20260102211820",
    "type": "arma",
    "name": "Espada Falcione",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-58-20260102211820",
    "type": "arma",
    "name": "Espada Flamberg",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-59-20260102211820",
    "type": "arma",
    "name": "Espada Gancho",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-60-20260102211820",
    "type": "arma",
    "name": "Espada larga",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-61-20260102211820",
    "type": "arma",
    "name": "Faca",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-62-20260102211820",
    "type": "arma",
    "name": "Forcado Militar",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-63-20260102211820",
    "type": "arma",
    "name": "Gancho, haste",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-64-20260102211820",
    "type": "arma",
    "name": "Glaive",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-65-20260102211820",
    "type": "arma",
    "name": "Godentag",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-66-20260102211820",
    "type": "arma",
    "name": "Guisarme",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-67-20260102211820",
    "type": "arma",
    "name": "Katar",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-68-20260102211820",
    "type": "arma",
    "name": "Lança",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-69-20260102211820",
    "type": "arma",
    "name": "Lança de lobo",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-70-20260102211820",
    "type": "arma",
    "name": "Lança leve",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-71-20260102211820",
    "type": "arma",
    "name": "Lança longa",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-72-20260102211820",
    "type": "arma",
    "name": "Maça grande",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-73-20260102211820",
    "type": "arma",
    "name": "Maça leve",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-74-20260102211820",
    "type": "arma",
    "name": "Maça estrela",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-75-20260102211820",
    "type": "arma",
    "name": "Machete",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-76-20260102211820",
    "type": "arma",
    "name": "Main Gauche",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-77-20260102211820",
    "type": "arma",
    "name": "Malho",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-78-20260102211820",
    "type": "arma",
    "name": "Manopla farpada",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-79-20260102211820",
    "type": "arma",
    "name": "Martelo de Lucerna",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-80-20260102211820",
    "type": "arma",
    "name": "Martelo de guerra",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-81-20260102211820",
    "type": "arma",
    "name": "Martelo leve",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-82-20260102211820",
    "type": "arma",
    "name": "Pegador",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-83-20260102211820",
    "type": "arma",
    "name": "Picareta de Guerra",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-84-20260102211820",
    "type": "arma",
    "name": "Picareta Leve",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-85-20260102211820",
    "type": "arma",
    "name": "Picareta Pesada",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-86-20260102211820",
    "type": "arma",
    "name": "Pique",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-87-20260102211820",
    "type": "arma",
    "name": "Poniard",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-88-20260102211820",
    "type": "arma",
    "name": "Porrete",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-89-20260102211820",
    "type": "arma",
    "name": "Punhal",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-90-20260102211820",
    "type": "arma",
    "name": "Punho",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-91-20260102211820",
    "type": "arma",
    "name": "Ranseur",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-92-20260102211820",
    "type": "arma",
    "name": "Sabre",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-93-20260102211820",
    "type": "arma",
    "name": "Sodegarami",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-94-20260102211820",
    "type": "armadura",
    "name": "Armadura Acolchoada",
    "effect": "CA +1",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-95-20260102211820",
    "type": "armadura",
    "name": "Armadura Completa",
    "effect": "CA +8",
    "gold": 1000,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-96-20260102211820",
    "type": "armadura",
    "name": "Armadura de Couro",
    "effect": "CA +2",
    "gold": 10,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-97-20260102211820",
    "type": "armadura",
    "name": "Armadura de Placas",
    "effect": "CA +7",
    "gold": 600,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-98-20260102211820",
    "type": "armadura",
    "name": "Brigandina",
    "effect": "CA +4",
    "gold": 85,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-99-20260102211820",
    "type": "armadura",
    "name": "Camisa de cota de Malha",
    "effect": "CA +4",
    "gold": 100,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-100-20260102211820",
    "type": "armadura",
    "name": "Casaco de Couro",
    "effect": "CA +1",
    "gold": 7,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-101-20260102211820",
    "type": "armadura",
    "name": "Conjunto completo (4)",
    "effect": "CA +7",
    "gold": 650,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-102-20260102211820",
    "type": "armadura",
    "name": "Conjunto Grego (1)",
    "effect": "CA +5",
    "gold": 120,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-103-20260102211820",
    "type": "armadura",
    "name": "Conjunto Grego (2)",
    "effect": "CA +6",
    "gold": 230,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-104-20260102211820",
    "type": "armadura",
    "name": "Conjunto Romano (3)",
    "effect": "CA +6",
    "gold": 240,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-105-20260102211820",
    "type": "armadura",
    "name": "Cota de Anéis",
    "effect": "CA +3",
    "gold": 30,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-106-20260102211820",
    "type": "armadura",
    "name": "Cota de bandas",
    "effect": "CA +6",
    "gold": 250,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-107-20260102211820",
    "type": "armadura",
    "name": "Cota de Escamas",
    "effect": "CA +4",
    "gold": 50,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-108-20260102211820",
    "type": "armadura",
    "name": "Cota de Malha Completa",
    "effect": "CA +6",
    "gold": 200,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-109-20260102211820",
    "type": "armadura",
    "name": "Cota de Placas",
    "effect": "CA +5",
    "gold": 100,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-110-20260102211820",
    "type": "armadura",
    "name": "Cota de talas",
    "effect": "CA +6",
    "gold": 200,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-111-20260102211820",
    "type": "armadura",
    "name": "Couro Batido",
    "effect": "CA +3",
    "gold": 25,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-112-20260102211820",
    "type": "armadura",
    "name": "Couro Cozido",
    "effect": "CA +4",
    "gold": 45,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-113-20260102211820",
    "type": "armadura",
    "name": "Hussarda Polonesa",
    "effect": "CA +8",
    "gold": 1750,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-114-20260102211820",
    "type": "armadura",
    "name": "Laminar de Couro",
    "effect": "CA +3",
    "gold": 55,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-115-20260102211820",
    "type": "armadura",
    "name": "Loriga de Cota de Malha",
    "effect": "CA +5",
    "gold": 150,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-116-20260102211820",
    "type": "armadura",
    "name": "Peitoral de Aço",
    "effect": "CA +5",
    "gold": 300,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-117-20260102211820",
    "type": "armadura",
    "name": "Peitoral de Bronze",
    "effect": "CA +4",
    "gold": 95,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-118-20260102211820",
    "type": "armadura",
    "name": "Peles",
    "effect": "CA +3",
    "gold": 20,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-119-20260102211820",
    "type": "barco",
    "name": "",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-120-20260102211820",
    "type": "distancia",
    "name": "Arco Curto",
    "effect": "dano 1d6 /18m",
    "gold": 30,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-121-20260102211820",
    "type": "distancia",
    "name": "Arco Longo",
    "effect": "dano 1d6 /30m",
    "gold": 75,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-122-20260102211820",
    "type": "distancia",
    "name": "Arco Longo Composto",
    "effect": "dano 1d8 /33m",
    "gold": 100,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-123-20260102211820",
    "type": "distancia",
    "name": "Azagaia",
    "effect": "dano 1d4 /9m",
    "gold": 1,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-124-20260102211820",
    "type": "distancia",
    "name": "Besta de Mão",
    "effect": "dano 1d4 /9m",
    "gold": 100,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-125-20260102211820",
    "type": "distancia",
    "name": "Besta Leve",
    "effect": "dano 1d6 /24m",
    "gold": 35,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-126-20260102211820",
    "type": "distancia",
    "name": "Besta Pesada",
    "effect": "dano 1d10 /36m",
    "gold": 50,
    "ev": 5,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-127-20260102211820",
    "type": "distancia",
    "name": "Bolas",
    "effect": "dano 1d4 /6m",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-128-20260102211820",
    "type": "distancia",
    "name": "Dardo",
    "effect": "dano 1d3 /6m",
    "gold": 0.5,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-129-20260102211820",
    "type": "distancia",
    "name": "Funda",
    "effect": "dano 1d4 /15m",
    "gold": 0,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "ilusionista",
      "mago",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-130-20260102211820",
    "type": "distancia",
    "name": "Arpão",
    "effect": "dano 1d6 /6m",
    "gold": 1,
    "ev": 5,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-131-20260102211820",
    "type": "distancia",
    "name": "Zarabatana",
    "effect": "dano 1 /3m",
    "gold": 1,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-132-20260102211820",
    "type": "distancia",
    "name": "Pedra",
    "effect": "dano 1d2 /9m",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-133-20260102211820",
    "type": "distancia",
    "name": "Aclis",
    "effect": "dano 1d4 /6m",
    "gold": 1,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-134-20260102211820",
    "type": "distancia",
    "name": "Boleadeira",
    "effect": "dano 1d4 /6m",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-135-20260102211820",
    "type": "elmo",
    "name": "Armete",
    "effect": "CA +6",
    "gold": 10,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-136-20260102211820",
    "type": "elmo",
    "name": "Barbuta",
    "effect": "CA+4",
    "gold": 15,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-137-20260102211820",
    "type": "elmo",
    "name": "Benin",
    "effect": "CA+2",
    "gold": 8,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-138-20260102211820",
    "type": "elmo",
    "name": "Casquete",
    "effect": "CA+2",
    "gold": 10,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-139-20260102211820",
    "type": "elmo",
    "name": "Chapéu de guerra",
    "effect": "CA+2",
    "gold": 7,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-140-20260102211820",
    "type": "elmo",
    "name": "Coifa, cota de malha",
    "effect": "CA+4",
    "gold": 15,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin",
      "ranger"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-141-20260102211820",
    "type": "elmo",
    "name": "Coifa, couro",
    "effect": "CA+1",
    "gold": 4,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassin",
      "bard",
      "bárbaro",
      "cleric",
      "druid",
      "fighter",
      "knight",
      "paladin",
      "ranger",
      "trapaceiro"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-142-20260102211820",
    "type": "elmo",
    "name": "Elmo, grande",
    "effect": "CA+7",
    "gold": 20,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-143-20260102211820",
    "type": "elmo",
    "name": "Elmo, normal",
    "effect": "CA+5",
    "gold": 10,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-144-20260102211820",
    "type": "elmo",
    "name": "Elmo, Normando",
    "effect": "CA+3",
    "gold": 8,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-145-20260102211820",
    "type": "elmo",
    "name": "Elmo, pote",
    "effect": "CA+2",
    "gold": 5,
    "ev": 1,
    "obs": "",
    "tags": "",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-146-20260102211820",
    "type": "equipamento",
    "name": "Água benta, frasco",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-147-20260102211820",
    "type": "equipamento",
    "name": "Algemas",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-148-20260102211820",
    "type": "equipamento",
    "name": "Aljava, dúzia",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-149-20260102211820",
    "type": "equipamento",
    "name": "Aljava, vinte",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-150-20260102211820",
    "type": "equipamento",
    "name": "Apito",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-151-20260102211820",
    "type": "equipamento",
    "name": "Armadilha grande de metal",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-152-20260102211820",
    "type": "equipamento",
    "name": "Armadilha média de metal",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-153-20260102211820",
    "type": "equipamento",
    "name": "Armadilha pequena de metal",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-154-20260102211820",
    "type": "equipamento",
    "name": "Balde",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-155-20260102211820",
    "type": "equipamento",
    "name": "Bandagens (2 ferimentos)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-156-20260102211820",
    "type": "equipamento",
    "name": "Bandolim",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-157-20260102211820",
    "type": "escudo",
    "name": "Broquel",
    "effect": "CA +1 (1)",
    "gold": 2,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "todos"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-158-20260102211820",
    "type": "escudo",
    "name": "Grande, Aço",
    "effect": "CA +1 (3)",
    "gold": 20,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "todos"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-159-20260102211820",
    "type": "escudo",
    "name": "Grande, Madeira",
    "effect": "CA +1 (3)",
    "gold": 7,
    "ev": 4,
    "obs": "",
    "tags": "",
    "proficience": [
      "todos"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-160-20260102211820",
    "type": "escudo",
    "name": "Médio, Aço",
    "effect": "CA +1 (2)",
    "gold": 15,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "todos"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-161-20260102211820",
    "type": "escudo",
    "name": "Médio, Madeira",
    "effect": "CA +1 (2)",
    "gold": 5,
    "ev": 3,
    "obs": "",
    "tags": "",
    "proficience": [
      "todos"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-162-20260102211820",
    "type": "escudo",
    "name": "Pavis",
    "effect": "CA +6 (4)",
    "gold": 55,
    "ev": 12,
    "obs": "",
    "tags": "",
    "proficience": [
      "todos"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-163-20260102211820",
    "type": "escudo",
    "name": "Pequeno, Aço",
    "effect": "CA +1 (1)",
    "gold": 9,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "todos"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-164-20260102211820",
    "type": "escudo",
    "name": "Pequeno, Madeira",
    "effect": "CA +1 (1)",
    "gold": 3,
    "ev": 2,
    "obs": "",
    "tags": "",
    "proficience": [
      "todos"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-165-20260102211820",
    "type": "estabulo",
    "name": "Curral, 1 Carroça",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-166-20260102211820",
    "type": "estabulo",
    "name": "Canil, 1 animal",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-167-20260102211820",
    "type": "estabulo",
    "name": "Estábulo, 1 Cavalo",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-168-20260102211820",
    "type": "estabulo",
    "name": "Estábulo, Camelo",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-169-20260102211820",
    "type": "estabulo",
    "name": "Estábulo, Javali",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-170-20260102211820",
    "type": "estabulo",
    "name": "Estábulo, Exótico (urso, etc.)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-171-20260102211820",
    "type": "municao",
    "name": "Flechas (20)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-172-20260102211820",
    "type": "municao",
    "name": "Flechas de Prata",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-173-20260102211820",
    "type": "municao",
    "name": "Virotes (12)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-174-20260102211820",
    "type": "municao",
    "name": "Flechas (12)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-175-20260102211820",
    "type": "provisoes",
    "name": "Cerveja Ale, Caneca",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-176-20260102211820",
    "type": "provisoes",
    "name": "Cerveja, Caneca",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-177-20260102211820",
    "type": "provisoes",
    "name": "Queijo, peça",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-178-20260102211820",
    "type": "provisoes",
    "name": "grãos, saco",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-179-20260102211820",
    "type": "provisoes",
    "name": "Licor, Barril",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-180-20260102211820",
    "type": "provisoes",
    "name": "Licor, Dose",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-181-20260102211820",
    "type": "provisoes",
    "name": "Hidromel, Caneca",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-182-20260102211820",
    "type": "provisoes",
    "name": "Rações (1 dia)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-183-20260102211820",
    "type": "provisoes",
    "name": "Rações (1 semana)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-184-20260102211820",
    "type": "provisoes",
    "name": "Refeição de taberna, comum",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-185-20260102211820",
    "type": "provisoes",
    "name": "Refeição de taberna, boa",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-186-20260102211820",
    "type": "provisoes",
    "name": "Folhas de chá, meio quilo",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-187-20260102211820",
    "type": "provisoes",
    "name": "Tabaco (meio quilo)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-188-20260102211820",
    "type": "provisoes",
    "name": "Vinho comum (garrafa)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-189-20260102211820",
    "type": "provisoes",
    "name": "Vinho fino (garrafa)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-190-20260102211820",
    "type": "provisoes",
    "name": "Refeição leve (peixe, pães, frutas, queijo)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-191-20260102211820",
    "type": "provisoes",
    "name": "Refeição pesada (carnes, vegetais, pães, manteiga)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-192-20260102211820",
    "type": "provisoes",
    "name": "Extravagante (carnes, pudins, frutas frias)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-193-20260102211820",
    "type": "provisoes",
    "name": "Cerveja clara",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-194-20260102211820",
    "type": "provisoes",
    "name": "Cerveja escura",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-195-20260102211820",
    "type": "provisoes",
    "name": "Cerveja lager",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-196-20260102211820",
    "type": "provisoes",
    "name": "Vinho vermelho/branco (garrafa)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-197-20260102211820",
    "type": "provisoes",
    "name": "Vinho Kathys Branco",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-198-20260102211820",
    "type": "roupas",
    "name": "Anel de sinete",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-199-20260102211820",
    "type": "roupas",
    "name": "Baldrico",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-200-20260102211820",
    "type": "roupas",
    "name": "Batina",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-201-20260102211820",
    "type": "roupas",
    "name": "Bijuterias",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-202-20260102211820",
    "type": "roupas",
    "name": "Boné/chapéu",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-203-20260102211820",
    "type": "roupas",
    "name": "Botas macias",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-204-20260102211820",
    "type": "roupas",
    "name": "Botas pesadas",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-205-20260102211820",
    "type": "roupas",
    "name": "Cachecol",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-206-20260102211820",
    "type": "roupas",
    "name": "Calças",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-207-20260102211820",
    "type": "roupas",
    "name": "Calças justas",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-208-20260102211820",
    "type": "roupas",
    "name": "Capa",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-209-20260102211820",
    "type": "roupas",
    "name": "Capuz",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-210-20260102211820",
    "type": "roupas",
    "name": "Cinto",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-211-20260102211820",
    "type": "roupas",
    "name": "Cinturão",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-212-20260102211820",
    "type": "roupas",
    "name": "Colete",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-213-20260102211820",
    "type": "roupas",
    "name": "Gibão",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-214-20260102211820",
    "type": "roupas",
    "name": "Jaleco",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-215-20260102211820",
    "type": "roupas",
    "name": "Kaftan",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-216-20260102211820",
    "type": "roupas",
    "name": "Luvas de couro",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-217-20260102211820",
    "type": "roupas",
    "name": "Luvas de tecido",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-218-20260102211820",
    "type": "roupas",
    "name": "Manto",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-219-20260102211820",
    "type": "roupas",
    "name": "Manto curto",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-220-20260102211820",
    "type": "roupas",
    "name": "Roupas de inverno, conjunto",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-221-20260102211820",
    "type": "roupas",
    "name": "Saia",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-222-20260102211820",
    "type": "roupas",
    "name": "Sapatos comuns",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-223-20260102211820",
    "type": "roupas",
    "name": "Túnica",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-224-20260102211820",
    "type": "roupas",
    "name": "Túnica longa",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-225-20260102211820",
    "type": "roupas",
    "name": "Vestido",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-226-20260102211820",
    "type": "roupas",
    "name": "Vestido de Serviço",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-227-20260102211820",
    "type": "transporte",
    "name": "Alforjes",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-228-20260102211820",
    "type": "transporte",
    "name": "Arreio",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-229-20260102211820",
    "type": "transporte",
    "name": "Barco a remo",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-230-20260102211820",
    "type": "transporte",
    "name": "Barco longo",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-231-20260102211820",
    "type": "transporte",
    "name": "Biga",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-232-20260102211820",
    "type": "transporte",
    "name": "Boi",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-233-20260102211820",
    "type": "transporte",
    "name": "Bote",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-234-20260102211820",
    "type": "transporte",
    "name": "Bote pequeno",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-235-20260102211820",
    "type": "transporte",
    "name": "Burro",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-236-20260102211820",
    "type": "transporte",
    "name": "Canoa",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-237-20260102211820",
    "type": "transporte",
    "name": "Carroça",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-238-20260102211820",
    "type": "transporte",
    "name": "Carroão",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-239-20260102211820",
    "type": "transporte",
    "name": "Carruagem",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-240-20260102211820",
    "type": "transporte",
    "name": "Cavalo de guerra leve",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-241-20260102211820",
    "type": "transporte",
    "name": "Cavalo de guerra pesado",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-242-20260102211820",
    "type": "transporte",
    "name": "Cavalo de passeio",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-243-20260102211820",
    "type": "transporte",
    "name": "Cavalo de tração",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-244-20260102211820",
    "type": "transporte",
    "name": "Cota de montaria, couro",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-245-20260102211820",
    "type": "transporte",
    "name": "Cota de montaria, couro curtido",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-246-20260102211820",
    "type": "transporte",
    "name": "Cota de montaria, malha",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-247-20260102211820",
    "type": "transporte",
    "name": "Cota de montaria, peles",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-248-20260102211820",
    "type": "transporte",
    "name": "Cota de montaria, placas",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-249-20260102211820",
    "type": "transporte",
    "name": "Freio e rédeas",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-250-20260102211820",
    "type": "transporte",
    "name": "Jangada",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-251-20260102211820",
    "type": "transporte",
    "name": "Manta de sela",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-252-20260102211820",
    "type": "transporte",
    "name": "Morsa",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-253-20260102211820",
    "type": "transporte",
    "name": "Mula",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-254-20260102211820",
    "type": "transporte",
    "name": "Pônei",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-255-20260102211820",
    "type": "transporte",
    "name": "Pônei de guerra",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-256-20260102211820",
    "type": "transporte",
    "name": "Ração (por dia)",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-257-20260102211820",
    "type": "transporte",
    "name": "Sela",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  },
  {
    "id": "ID-258-20260102211820",
    "type": "transporte",
    "name": "Trenó",
    "effect": "",
    "gold": 0,
    "ev": null,
    "obs": "",
    "tags": "",
    "proficience": [],
    "icon": "dagger-black",
    "image": "undefined"
  }
]