import type { Item } from './use-items';

export const items: Item[] = [
  {
    "id": "ID-2-20260103155224",
    "type": "alojamento",
    "name": "1 Cama mobiliada",
    "gold": 1,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-3-20260103155224",
    "type": "alojamento",
    "name": "1 cama sem mobiliário",
    "gold": 0.8,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-4-20260103155224",
    "type": "alojamento",
    "name": "2 Camas mobiliadas",
    "gold": 2,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-5-20260103155224",
    "type": "alojamento",
    "name": "2 camas sem mobiliário",
    "gold": 1.5,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-6-20260103155224",
    "type": "alojamento",
    "name": "4 Camas mobiliadas",
    "gold": 10,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-7-20260103155224",
    "type": "alojamento",
    "name": "4 camas sem mobiliário",
    "gold": 5,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-8-20260103155224",
    "type": "alojamento",
    "name": "5+ Camas mobiliadas (+1 PO por cama extra)",
    "gold": 1,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-9-20260103155224",
    "type": "alojamento",
    "name": "5+ Camas sem mobiliário (+15 PP por cama extra)",
    "gold": 1.5,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-10-20260103155224",
    "type": "distancia",
    "name": "Aclis",
    "gold": 1,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d4 /6m",
    "proficience": [],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-11-20260103155224",
    "type": "arma",
    "name": "Adaga",
    "gold": 2,
    "ev": 2,
    "obs": "projetil",
    "effect": "dano 1d4 /6m",
    "proficience": [
      "assassino",
      "trapaceiro"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-12-20260103155224",
    "type": "equipamento",
    "name": "Água benta, frasco",
    "gold": 30,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-13-20260103155224",
    "type": "arma",
    "name": "Alabarda",
    "gold": 10,
    "ev": 5,
    "obs": "2 mãos, haste",
    "effect": "dano 1d10",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-14-20260103155224",
    "type": "transporte",
    "name": "Alforjes",
    "gold": 4,
    "ev": 3,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-15-20260103155224",
    "type": "equipamento",
    "name": "Algemas",
    "gold": 15,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-16-20260103155224",
    "type": "equipamento",
    "name": "Aljava, dúzia",
    "gold": 2,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-17-20260103155224",
    "type": "equipamento",
    "name": "Aljava, vinte",
    "gold": 4,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-18-20260103155224",
    "type": "roupas",
    "name": "Anel de sinete",
    "gold": 15,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-19-20260103155224",
    "type": "equipamento",
    "name": "Apito",
    "gold": 0.5,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-20-20260103155224",
    "type": "distancia",
    "name": "Arco Curto",
    "gold": 30,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d6 /18m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-21-20260103155224",
    "type": "distancia",
    "name": "Arco Longo",
    "gold": 75,
    "ev": 4,
    "obs": "",
    "effect": "dano 1d6 /30m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-22-20260103155224",
    "type": "distancia",
    "name": "Arco Longo Composto",
    "gold": 100,
    "ev": 4,
    "obs": "",
    "effect": "dano 1d8 /33m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-23-20260103155224",
    "type": "equipamento",
    "name": "Armadilha grande de metal",
    "gold": 35,
    "ev": 9,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-24-20260103155224",
    "type": "equipamento",
    "name": "Armadilha média de metal",
    "gold": 15,
    "ev": 6,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-25-20260103155224",
    "type": "equipamento",
    "name": "Armadilha pequena de metal",
    "gold": 7,
    "ev": 3,
    "obs": "capacidade 3",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-26-20260103155224",
    "type": "armadura",
    "name": "Armadura Acolchoada",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "effect": "CA +1",
    "proficience": [
      "trapaceiro"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-27-20260103155224",
    "type": "armadura",
    "name": "Armadura Completa",
    "gold": 1000,
    "ev": 4,
    "obs": "",
    "effect": "CA +8",
    "proficience": [],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-28-20260103155224",
    "type": "armadura",
    "name": "Armadura de Couro",
    "gold": 10,
    "ev": 2,
    "obs": "",
    "effect": "CA +2",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino",
      "trapaceiro"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-29-20260103155224",
    "type": "armadura",
    "name": "Armadura de Placas",
    "gold": 600,
    "ev": 4,
    "obs": "",
    "effect": "CA +7",
    "proficience": [],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-30-20260103155224",
    "type": "elmo",
    "name": "Armete",
    "gold": 10,
    "ev": 1,
    "obs": "",
    "effect": "CA+6",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "helm",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-31-20260103155224",
    "type": "distancia",
    "name": "Arpão",
    "gold": 1,
    "ev": 5,
    "obs": "",
    "effect": "dano 1d6 /6m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-32-20260103155224",
    "type": "transporte",
    "name": "Arreio",
    "gold": 1,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-33-20260103155224",
    "type": "distancia",
    "name": "Azagaia",
    "gold": 1,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d4 /9m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-34-20260103155224",
    "type": "equipamento",
    "name": "Balde",
    "gold": 0.5,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-35-20260103155224",
    "type": "roupas",
    "name": "Baldrico",
    "gold": 0.2,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-36-20260103155224",
    "type": "equipamento",
    "name": "Bandagens (2 ferimentos)",
    "gold": 1,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-37-20260103155224",
    "type": "equipamento",
    "name": "Bandolim",
    "gold": 10,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-38-20260103155224",
    "type": "elmo",
    "name": "Barbuta",
    "gold": 15,
    "ev": 1,
    "obs": "",
    "effect": "CA+4",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "helm",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-39-20260103155224",
    "type": "transporte",
    "name": "Barco a remo",
    "gold": 50,
    "ev": 25,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-40-20260103155224",
    "type": "transporte",
    "name": "Barco longo",
    "gold": 500,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-41-20260103155224",
    "type": "roupas",
    "name": "Batina",
    "gold": 0.5,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-42-20260103155224",
    "type": "elmo",
    "name": "Benin",
    "gold": 8,
    "ev": 1,
    "obs": "",
    "effect": "CA+2",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "helm",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-43-20260103155224",
    "type": "distancia",
    "name": "Besta de Mão",
    "gold": 100,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d4 /9m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-44-20260103155224",
    "type": "distancia",
    "name": "Besta Leve",
    "gold": 35,
    "ev": 4,
    "obs": "",
    "effect": "dano 1d6 /24m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-45-20260103155224",
    "type": "distancia",
    "name": "Besta Pesada",
    "gold": 50,
    "ev": 5,
    "obs": "",
    "effect": "dano 1d10 /36m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-46-20260103155224",
    "type": "transporte",
    "name": "Biga",
    "gold": 200,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-47-20260103155224",
    "type": "roupas",
    "name": "Bijuterias",
    "gold": 0,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-48-20260103155224",
    "type": "transporte",
    "name": "Boi",
    "gold": 18,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-49-20260103155224",
    "type": "distancia",
    "name": "Bolas",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d4 /6m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-50-20260103155224",
    "type": "distancia",
    "name": "Boleadeira",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d4 /6m",
    "proficience": [],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-51-20260103155224",
    "type": "roupas",
    "name": "Boné/chapéu",
    "gold": 0.4,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-52-20260103155224",
    "type": "roupas",
    "name": "Botas macias",
    "gold": 0.4,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-53-20260103155224",
    "type": "roupas",
    "name": "Botas pesadas",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-54-20260103155224",
    "type": "transporte",
    "name": "Bote",
    "gold": 300,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-55-20260103155224",
    "type": "transporte",
    "name": "Bote pequeno",
    "gold": 250,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-56-20260103155224",
    "type": "armadura",
    "name": "Brigandina",
    "gold": 85,
    "ev": 4,
    "obs": "",
    "effect": "CA +4",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-57-20260103155224",
    "type": "escudo",
    "name": "Broquel",
    "gold": 2,
    "ev": 2,
    "obs": "",
    "effect": "CA +1 (1)",
    "proficience": [
      "todos"
    ],
    "icon": "shield",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-58-20260103155224",
    "type": "transporte",
    "name": "Burro",
    "gold": 8,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-59-20260103155224",
    "type": "roupas",
    "name": "Cachecol",
    "gold": 0.05,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-60-20260103155224",
    "type": "arma",
    "name": "Cajado",
    "gold": 0,
    "ev": 4,
    "obs": "",
    "effect": "dano 1d6",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-61-20260103155224",
    "type": "roupas",
    "name": "Calças",
    "gold": 0.4,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-62-20260103155224",
    "type": "roupas",
    "name": "Calças justas",
    "gold": 0.5,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-63-20260103155224",
    "type": "armadura",
    "name": "Camisa de cota de Malha",
    "gold": 100,
    "ev": 3,
    "obs": "",
    "effect": "CA +4",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-64-20260103155224",
    "type": "estabulo",
    "name": "Canil, 1 animal",
    "gold": 0.1,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "horses",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-65-20260103155224",
    "type": "transporte",
    "name": "Canoa",
    "gold": 35,
    "ev": 23,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-66-20260103155224",
    "type": "roupas",
    "name": "Capa",
    "gold": 0.8,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-67-20260103155224",
    "type": "roupas",
    "name": "Capuz",
    "gold": 0.2,
    "ev": 3,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-68-20260103155224",
    "type": "transporte",
    "name": "Carroção",
    "gold": 35,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-69-20260103155224",
    "type": "transporte",
    "name": "Carroça",
    "gold": 15,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-70-20260103155224",
    "type": "transporte",
    "name": "Carruagem",
    "gold": 100,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-71-20260103155224",
    "type": "armadura",
    "name": "Casaco de Couro",
    "gold": 7,
    "ev": 2,
    "obs": "",
    "effect": "CA +1",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino",
      "trapaceiro"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-72-20260103155224",
    "type": "elmo",
    "name": "Casquete",
    "gold": 10,
    "ev": 1,
    "obs": "",
    "effect": "CA+2",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "helm",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-73-20260103155224",
    "type": "transporte",
    "name": "Cavalo de guerra leve",
    "gold": 150,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-74-20260103155224",
    "type": "transporte",
    "name": "Cavalo de guerra pesado",
    "gold": 400,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-75-20260103155224",
    "type": "transporte",
    "name": "Cavalo de passeio",
    "gold": 75,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-76-20260103155224",
    "type": "transporte",
    "name": "Cavalo de tração",
    "gold": 200,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-77-20260103155224",
    "type": "provisoes",
    "name": "Cerveja Ale, Caneca",
    "gold": 0.05,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-78-20260103155224",
    "type": "provisoes",
    "name": "Cerveja clara",
    "gold": 0.02,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-79-20260103155224",
    "type": "provisoes",
    "name": "Cerveja escura",
    "gold": 0.05,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-80-20260103155224",
    "type": "provisoes",
    "name": "Cerveja lager",
    "gold": 0.1,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-81-20260103155224",
    "type": "provisoes",
    "name": "Cerveja, Caneca",
    "gold": 0.02,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-82-20260103155224",
    "type": "arma",
    "name": "Cestus",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "dano +1",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-83-20260103155224",
    "type": "elmo",
    "name": "Chapéu de guerra",
    "gold": 7,
    "ev": 1,
    "obs": "",
    "effect": "CA+2",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "helm",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-84-20260103155224",
    "type": "arma",
    "name": "Chicote",
    "gold": 1,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d2 /4.5m",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-85-20260103155224",
    "type": "roupas",
    "name": "Cinto",
    "gold": 0.6,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-86-20260103155224",
    "type": "roupas",
    "name": "Cinturão",
    "gold": 0.7,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-87-20260103155224",
    "type": "arma",
    "name": "Clava",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d3 /6m",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-88-20260103155224",
    "type": "arma",
    "name": "Clava pesada",
    "gold": 15,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d6+1",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-89-20260103155224",
    "type": "elmo",
    "name": "Coifa, cota de malha",
    "gold": 15,
    "ev": 1,
    "obs": "",
    "effect": "CA+4",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin",
      "ranger"
    ],
    "icon": "helm",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-90-20260103155224",
    "type": "elmo",
    "name": "Coifa, couro",
    "gold": 4,
    "ev": 1,
    "obs": "",
    "effect": "CA+1",
    "proficience": [
      "assassin",
      "bard",
      "bárbaro",
      "cleric",
      "druid",
      "fighter",
      "knight",
      "paladin",
      "ranger",
      "trapaceiro"
    ],
    "icon": "helm",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-91-20260103155224",
    "type": "roupas",
    "name": "Colete",
    "gold": 0.2,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-92-20260103155224",
    "type": "alojamento",
    "name": "Comum (piso de palha)",
    "gold": 0.05,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-93-20260103155224",
    "type": "armadura",
    "name": "Conjunto completo (4)",
    "gold": 650,
    "ev": 4,
    "obs": "",
    "effect": "CA +7",
    "proficience": [],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-94-20260103155224",
    "type": "armadura",
    "name": "Conjunto Grego (1)",
    "gold": 120,
    "ev": 4,
    "obs": "",
    "effect": "CA +5",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-95-20260103155224",
    "type": "armadura",
    "name": "Conjunto Grego (2)",
    "gold": 230,
    "ev": 4,
    "obs": "",
    "effect": "CA +6",
    "proficience": [
      "assassino",
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-96-20260103155224",
    "type": "armadura",
    "name": "Conjunto Romano (3)",
    "gold": 240,
    "ev": 4,
    "obs": "",
    "effect": "CA +6",
    "proficience": [
      "assassino",
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-97-20260103155224",
    "type": "armadura",
    "name": "Cota de Anéis",
    "gold": 30,
    "ev": 3,
    "obs": "",
    "effect": "CA +3",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-98-20260103155224",
    "type": "armadura",
    "name": "Cota de bandas",
    "gold": 250,
    "ev": 4,
    "obs": "",
    "effect": "CA +6",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-99-20260103155224",
    "type": "armadura",
    "name": "Cota de Escamas",
    "gold": 50,
    "ev": 4,
    "obs": "",
    "effect": "CA +4",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-100-20260103155224",
    "type": "armadura",
    "name": "Cota de Malha Completa",
    "gold": 200,
    "ev": 4,
    "obs": "",
    "effect": "CA +6",
    "proficience": [],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-101-20260103155224",
    "type": "transporte",
    "name": "Cota de montaria, couro",
    "gold": 50,
    "ev": 5,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-102-20260103155224",
    "type": "transporte",
    "name": "Cota de montaria, couro curtido",
    "gold": 100,
    "ev": 6,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-103-20260103155224",
    "type": "transporte",
    "name": "Cota de montaria, malha",
    "gold": 500,
    "ev": 6,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-104-20260103155224",
    "type": "transporte",
    "name": "Cota de montaria, peles",
    "gold": 20,
    "ev": 5,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-105-20260103155224",
    "type": "transporte",
    "name": "Cota de montaria, placas",
    "gold": 4000,
    "ev": 8,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-106-20260103155224",
    "type": "armadura",
    "name": "Cota de Placas",
    "gold": 100,
    "ev": 4,
    "obs": "",
    "effect": "CA +5",
    "proficience": [
      "assassino",
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-107-20260103155224",
    "type": "armadura",
    "name": "Cota de talas",
    "gold": 200,
    "ev": 4,
    "obs": "",
    "effect": "CA +6",
    "proficience": [
      "assassino",
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-108-20260103155224",
    "type": "armadura",
    "name": "Couro Batido",
    "gold": 25,
    "ev": 3,
    "obs": "",
    "effect": "CA +3",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino",
      "trapaceiro"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-109-20260103155224",
    "type": "armadura",
    "name": "Couro Cozido",
    "gold": 45,
    "ev": 4,
    "obs": "",
    "effect": "CA +4",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino",
      "trapaceiro"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-110-20260103155224",
    "type": "transporte",
    "name": "Curral, 1 Carroça",
    "gold": 0.3,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-111-20260103155224",
    "type": "arma",
    "name": "Cutelo",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d4",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-112-20260103155224",
    "type": "arma",
    "name": "Cutelo longo",
    "gold": 8,
    "ev": 5,
    "obs": "dano 1d12 com 2 mãos, haste",
    "effect": "dano 2d4",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-113-20260103155224",
    "type": "distancia",
    "name": "Dardo",
    "gold": 0.5,
    "ev": 1,
    "obs": "",
    "effect": "dano 1d3 /6m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-114-20260103155224",
    "type": "elmo",
    "name": "Elmo, grande",
    "gold": 20,
    "ev": 2,
    "obs": "",
    "effect": "CA+7",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "helm",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-115-20260103155224",
    "type": "elmo",
    "name": "Elmo, normal",
    "gold": 10,
    "ev": 1,
    "obs": "",
    "effect": "CA+5",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "helm",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-116-20260103155224",
    "type": "elmo",
    "name": "Elmo, Normando",
    "gold": 8,
    "ev": 1,
    "obs": "",
    "effect": "CA+3",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "helm",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-117-20260103155224",
    "type": "elmo",
    "name": "Elmo, pote",
    "gold": 5,
    "ev": 1,
    "obs": "",
    "effect": "CA+2",
    "proficience": [
      "bárbaro",
      "cleric",
      "fighter",
      "knight",
      "paladin"
    ],
    "icon": "helm",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-118-20260103155224",
    "type": "arma",
    "name": "Espada Bastarda",
    "gold": 25,
    "ev": 4,
    "obs": "dano 1d12 com 2 mãos",
    "effect": "dano 1d10",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-119-20260103155224",
    "type": "arma",
    "name": "Espada Broadsword",
    "gold": 12,
    "ev": 4,
    "obs": "",
    "effect": "dano 2d4",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-120-20260103155224",
    "type": "arma",
    "name": "Espada Cimitarra",
    "gold": 15,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d6",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-121-20260103155224",
    "type": "arma",
    "name": "Espada Cimitarra grande",
    "gold": 55,
    "ev": 4,
    "obs": "",
    "effect": "2d6",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-122-20260103155224",
    "type": "arma",
    "name": "Espada Curta",
    "gold": 10,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d6",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-123-20260103155224",
    "type": "arma",
    "name": "Espada de duas mãos",
    "gold": 30,
    "ev": 5,
    "obs": "2 mãos",
    "effect": "dano 2d6",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-124-20260103155224",
    "type": "arma",
    "name": "Espada de Gancho",
    "gold": 25,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d4+1",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "ilusionista",
      "mago",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-125-20260103155224",
    "type": "arma",
    "name": "Espada Falcione",
    "gold": 40,
    "ev": 3,
    "obs": "",
    "effect": "dano 2d4",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-126-20260103155224",
    "type": "arma",
    "name": "Espada Flamberg",
    "gold": 75,
    "ev": 4,
    "obs": "2 mãos",
    "effect": "2d4+2",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-127-20260103155224",
    "type": "arma",
    "name": "Espada Gancho",
    "gold": 25,
    "ev": 3,
    "obs": "desarmar/subjugar +3",
    "effect": "1d4+1",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-128-20260103155224",
    "type": "arma",
    "name": "Espada larga",
    "gold": 12,
    "ev": 4,
    "obs": "",
    "effect": "2d4",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-129-20260103155224",
    "type": "arma",
    "name": "Espada larga, 9 anéis",
    "gold": 30,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d10",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-130-20260103155224",
    "type": "arma",
    "name": "Espada Longa",
    "gold": 15,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d8",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-131-20260103155224",
    "type": "arma",
    "name": "Espada Rapieira",
    "gold": 20,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d6",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-132-20260103155224",
    "type": "estabulo",
    "name": "Estábulo, 1 Cavalo",
    "gold": 0.1,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "horses",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-133-20260103155224",
    "type": "estabulo",
    "name": "Estábulo, Camelo",
    "gold": 0.5,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "horses",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-134-20260103155224",
    "type": "estabulo",
    "name": "Estábulo, Exótico (urso, etc.)",
    "gold": 1,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "horses",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-135-20260103155224",
    "type": "estabulo",
    "name": "Estábulo, Javali",
    "gold": 0.3,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "horses",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-136-20260103155224",
    "type": "alojamento",
    "name": "Estalagem Boa",
    "gold": 2,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-137-20260103155224",
    "type": "alojamento",
    "name": "Estalagem comum",
    "gold": 0.5,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-138-20260103155224",
    "type": "alojamento",
    "name": "Estalagem Pobre",
    "gold": 0.1,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-139-20260103155224",
    "type": "provisoes",
    "name": "Refeição Extravagante (carnes, pudins, frutas frias)",
    "gold": 1,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-140-20260103155224",
    "type": "arma",
    "name": "Faca",
    "gold": 0.3,
    "ev": 1,
    "obs": "projetil",
    "effect": "dano 1d2 /6m",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-141-20260103155224",
    "type": "municao",
    "name": "Flechas (12)",
    "gold": 1.5,
    "ev": 1,
    "obs": "arco",
    "effect": "",
    "proficience": [],
    "icon": "arrows",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-142-20260103155224",
    "type": "municao",
    "name": "Flechas (20)",
    "gold": 2,
    "ev": 2,
    "obs": "arco",
    "effect": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "arrows",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-143-20260103155224",
    "type": "municao",
    "name": "Flechas de Prata (2)",
    "gold": 2,
    "ev": 1,
    "obs": "arco",
    "effect": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "arrows",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-144-20260103155224",
    "type": "arma",
    "name": "Foice de Guerra",
    "gold": 18,
    "ev": 4,
    "obs": "",
    "effect": "dano 2d4",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-145-20260103155224",
    "type": "provisoes",
    "name": "Folhas de chá, meio quilo",
    "gold": 0.1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-146-20260103155224",
    "type": "arma",
    "name": "Forcado Militar",
    "gold": 10,
    "ev": 5,
    "obs": "2 mãos, haste",
    "effect": "dano 1d8",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-147-20260103155224",
    "type": "transporte",
    "name": "Freio e rédeas",
    "gold": 1,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-148-20260103155224",
    "type": "distancia",
    "name": "Funda",
    "gold": 0,
    "ev": 1,
    "obs": "",
    "effect": "dano 1d4 /15m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "ilusionista",
      "mago",
      "paladino",
      "trapaceiro"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-149-20260103155224",
    "type": "arma",
    "name": "Gancho, haste",
    "gold": 5,
    "ev": 4,
    "obs": "haste",
    "effect": "dano 1d6",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-150-20260103155224",
    "type": "arma",
    "name": "Garfo Fauchard",
    "gold": 15,
    "ev": 5,
    "obs": "2 mãos, haste",
    "effect": "dano 1d8 /3m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-151-20260103155224",
    "type": "arma",
    "name": "Garfo militar",
    "gold": 10,
    "ev": 5,
    "obs": "",
    "effect": "dano 1d8",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-152-20260103155224",
    "type": "arma",
    "name": "Gato de nove caudas",
    "gold": 9,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d3",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-153-20260103155224",
    "type": "roupas",
    "name": "Gibão",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-154-20260103155224",
    "type": "arma",
    "name": "Glaive",
    "gold": 8,
    "ev": 5,
    "obs": "2 mãos",
    "effect": "dano 1d8 /3m",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-155-20260103155224",
    "type": "arma",
    "name": "Godentag",
    "gold": 15,
    "ev": 3,
    "obs": "2 mãos",
    "effect": "dano 1d6+3",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-156-20260103155224",
    "type": "escudo",
    "name": "Grande, Aço",
    "gold": 20,
    "ev": 4,
    "obs": "",
    "effect": "CA +1 (3)",
    "proficience": [
      "todos"
    ],
    "icon": "shield",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-157-20260103155224",
    "type": "escudo",
    "name": "Grande, Madeira",
    "gold": 7,
    "ev": 4,
    "obs": "",
    "effect": "CA +1 (3)",
    "proficience": [
      "todos"
    ],
    "icon": "shield",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-158-20260103155224",
    "type": "provisoes",
    "name": "grãos, saco",
    "gold": 0,
    "ev": 3,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-159-20260103155224",
    "type": "arma",
    "name": "Guisarme",
    "gold": 10,
    "ev": 5,
    "obs": "2 mãos, haste",
    "effect": "dano 2d4 /3m",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-160-20260103155224",
    "type": "provisoes",
    "name": "Hidromel, Caneca",
    "gold": 0.2,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-161-20260103155224",
    "type": "armadura",
    "name": "Hussarda Polonesa",
    "gold": 1750,
    "ev": 3,
    "obs": "",
    "effect": "CA +8",
    "proficience": [],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-162-20260103155224",
    "type": "roupas",
    "name": "Jaleco",
    "gold": 0.3,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-163-20260103155224",
    "type": "transporte",
    "name": "Jangada",
    "gold": 100,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-164-20260103155224",
    "type": "roupas",
    "name": "Kaftan",
    "gold": 0.3,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-165-20260103155224",
    "type": "arma",
    "name": "Katar",
    "gold": 3,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d4+1",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-166-20260103155224",
    "type": "armadura",
    "name": "Laminar de Couro",
    "gold": 55,
    "ev": 2,
    "obs": "",
    "effect": "CA +3",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino",
      "trapaceiro"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-167-20260103155224",
    "type": "arma",
    "name": "Lança",
    "gold": 1,
    "ev": 2,
    "obs": "investida montada dano 2x",
    "effect": "dano 1d6 /9m",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-168-20260103155224",
    "type": "arma",
    "name": "Lança de lobo",
    "gold": 3,
    "ev": 3,
    "obs": "projetil",
    "effect": "dano 1d8 /6m",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-169-20260103155224",
    "type": "arma",
    "name": "Lança leve",
    "gold": 6,
    "ev": 5,
    "obs": "investida montada dano 2x",
    "effect": "dano 1d6",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-170-20260103155224",
    "type": "arma",
    "name": "Lança longa",
    "gold": 5,
    "ev": 4,
    "obs": "projetil, receber investida dano 2x, haste",
    "effect": "dano 1d8 /3m",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-171-20260103155224",
    "type": "arma",
    "name": "Lança Partisan",
    "gold": 10,
    "ev": 5,
    "obs": "2 mãos, haste",
    "effect": "dano 1d8 /3m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-172-20260103155224",
    "type": "arma",
    "name": "Lança Pesada",
    "gold": 10,
    "ev": 7,
    "obs": "investida montada dano 2x",
    "effect": "dano 1d8",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-173-20260103155224",
    "type": "provisoes",
    "name": "Licor, Barril",
    "gold": 25,
    "ev": 5,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-174-20260103155224",
    "type": "provisoes",
    "name": "Licor, Dose",
    "gold": 0.2,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-175-20260103155224",
    "type": "armadura",
    "name": "Loriga de Cota de Malha",
    "gold": 150,
    "ev": 4,
    "obs": "",
    "effect": "CA +5",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-176-20260103155224",
    "type": "roupas",
    "name": "Luvas de couro",
    "gold": 0.8,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-177-20260103155224",
    "type": "roupas",
    "name": "Luvas de tecido",
    "gold": 0.2,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-178-20260103155224",
    "type": "arma",
    "name": "Maça estrela",
    "gold": 8,
    "ev": 3,
    "obs": "",
    "effect": "dano 2d4",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-179-20260103155224",
    "type": "arma",
    "name": "Maça grande",
    "gold": 25,
    "ev": 4,
    "obs": "investida montada dano 2x",
    "effect": "dano 1d10",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-180-20260103155224",
    "type": "arma",
    "name": "Maça leve",
    "gold": 5,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d6",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-181-20260103155224",
    "type": "arma",
    "name": "Maça Pesada",
    "gold": 12,
    "ev": 4,
    "obs": "",
    "effect": "dano 1d8",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-182-20260103155224",
    "type": "arma",
    "name": "Machado Barbado",
    "gold": 20,
    "ev": 4,
    "obs": "2 mãos",
    "effect": "dano 3d4",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-183-20260103155224",
    "type": "arma",
    "name": "Machado Bardiche",
    "gold": 15,
    "ev": 4,
    "obs": "2 mãos, haste",
    "effect": "dano 2d4",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-184-20260103155224",
    "type": "arma",
    "name": "Machado de arremesso",
    "gold": 4,
    "ev": 2,
    "obs": "projetil",
    "effect": "dano 1d6",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-185-20260103155224",
    "type": "arma",
    "name": "Machado de Batalha",
    "gold": 10,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d8",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-186-20260103155224",
    "type": "arma",
    "name": "Machado de duas mãos",
    "gold": 20,
    "ev": 4,
    "obs": "2 mãos",
    "effect": "dano 1d12",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-187-20260103155224",
    "type": "arma",
    "name": "Machado, perfurador",
    "gold": 17,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d8+1",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-188-20260103155224",
    "type": "arma",
    "name": "Machete",
    "gold": 1,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d4",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-189-20260103155224",
    "type": "arma",
    "name": "Main Gauche",
    "gold": 25,
    "ev": 2,
    "obs": "CA +1",
    "effect": "dano 1d4+1",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-190-20260103155224",
    "type": "arma",
    "name": "Malho",
    "gold": 12,
    "ev": 5,
    "obs": "2 mãos",
    "effect": "dano 1d10",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-191-20260103155224",
    "type": "arma",
    "name": "Mangual Leve",
    "gold": 8,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d8",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-192-20260103155224",
    "type": "arma",
    "name": "Mangual Pesado",
    "gold": 15,
    "ev": 4,
    "obs": "2 mãos",
    "effect": "dano 1d10",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-193-20260103155224",
    "type": "arma",
    "name": "Manopla farpada",
    "gold": 5,
    "ev": 1,
    "obs": "",
    "effect": "dano 1d3",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-194-20260103155224",
    "type": "transporte",
    "name": "Manta de sela",
    "gold": 0.5,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-195-20260103155224",
    "type": "roupas",
    "name": "Manto",
    "gold": 0.5,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-196-20260103155224",
    "type": "roupas",
    "name": "Manto curto",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-197-20260103155224",
    "type": "arma",
    "name": "Marreta",
    "gold": 12,
    "ev": 5,
    "obs": "",
    "effect": "dano 1d10",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-198-20260103155224",
    "type": "arma",
    "name": "Martelo de guerra",
    "gold": 6,
    "ev": 4,
    "obs": "",
    "effect": "dano 1d8",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-199-20260103155224",
    "type": "arma",
    "name": "Martelo de Lucerna",
    "gold": 60,
    "ev": 5,
    "obs": "2 mãos, haste",
    "effect": "dano 1d12",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-200-20260103155224",
    "type": "arma",
    "name": "Martelo leve",
    "gold": 1,
    "ev": 2,
    "obs": "projetil",
    "effect": "dano 1d4 /9m",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-201-20260103155224",
    "type": "escudo",
    "name": "Médio, Aço",
    "gold": 15,
    "ev": 3,
    "obs": "",
    "effect": "CA +1 (2)",
    "proficience": [
      "todos"
    ],
    "icon": "shield",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-202-20260103155224",
    "type": "escudo",
    "name": "Médio, Madeira",
    "gold": 5,
    "ev": 3,
    "obs": "",
    "effect": "CA +1 (2)",
    "proficience": [
      "todos"
    ],
    "icon": "shield",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-203-20260103155224",
    "type": "arma",
    "name": "Morningstar",
    "gold": 8,
    "ev": 3,
    "obs": "",
    "effect": "dano 2d4",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-204-20260103155224",
    "type": "transporte",
    "name": "Morsa",
    "gold": 350,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-205-20260103155224",
    "type": "transporte",
    "name": "Mula",
    "gold": 25,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-206-20260103155224",
    "type": "escudo",
    "name": "Pavis",
    "gold": 55,
    "ev": 12,
    "obs": "",
    "effect": "CA +6 (4)",
    "proficience": [
      "todos"
    ],
    "icon": "shield",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-207-20260103155224",
    "type": "distancia",
    "name": "Pedra",
    "gold": 0,
    "ev": null,
    "obs": "",
    "effect": "dano 1d2 /9m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-208-20260103155224",
    "type": "arma",
    "name": "Pegador",
    "gold": 45,
    "ev": 4,
    "obs": "agarra CA 15 + NV, 2 mãos",
    "effect": "dano 1d4",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-209-20260103155224",
    "type": "armadura",
    "name": "Peitoral de Aço",
    "gold": 300,
    "ev": 3,
    "obs": "",
    "effect": "CA +5",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-210-20260103155224",
    "type": "armadura",
    "name": "Peitoral de Bronze",
    "gold": 95,
    "ev": 3,
    "obs": "",
    "effect": "CA +4",
    "proficience": [
      "bardo",
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-211-20260103155224",
    "type": "armadura",
    "name": "Peles",
    "gold": 20,
    "ev": 4,
    "obs": "",
    "effect": "CA +3",
    "proficience": [
      "bárbaro",
      "cavaleiro",
      "clerigo",
      "combatente",
      "paladino"
    ],
    "icon": "armor",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-212-20260103155224",
    "type": "escudo",
    "name": "Pequeno, Aço",
    "gold": 9,
    "ev": 2,
    "obs": "",
    "effect": "CA +1 (1)",
    "proficience": [
      "todos"
    ],
    "icon": "shield",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-213-20260103155224",
    "type": "escudo",
    "name": "Pequeno, Madeira",
    "gold": 3,
    "ev": 2,
    "obs": "",
    "effect": "CA +1 (1)",
    "proficience": [
      "todos"
    ],
    "icon": "shield",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-214-20260103155224",
    "type": "arma",
    "name": "Picareta bico de corvo",
    "gold": 12,
    "ev": 5,
    "obs": "+2 vs malha, placas, escamas, 2 mãos, haste",
    "effect": "dano 1d10",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino",
      "trapaceiro"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-215-20260103155224",
    "type": "arma",
    "name": "Picareta de Guerra",
    "gold": 15,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d6",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-216-20260103155224",
    "type": "arma",
    "name": "Picareta Leve",
    "gold": 4,
    "ev": 3,
    "obs": "",
    "effect": "dano 1d4",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-217-20260103155224",
    "type": "arma",
    "name": "Picareta Pesada",
    "gold": 8,
    "ev": 4,
    "obs": "",
    "effect": "dano 1d6",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-218-20260103155224",
    "type": "arma",
    "name": "Pique",
    "gold": 5,
    "ev": 6,
    "obs": "receber investida dano 2x, 2 mãos, haste",
    "effect": "dano 1d8 /3m",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-219-20260103155224",
    "type": "arma",
    "name": "Podão ou gancho",
    "gold": 12,
    "ev": 5,
    "obs": "2 mãos, haste",
    "effect": "dano 2d4",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-220-20260103155224",
    "type": "transporte",
    "name": "Pônei",
    "gold": 30,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-221-20260103155224",
    "type": "transporte",
    "name": "Pônei de guerra",
    "gold": 100,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-222-20260103155224",
    "type": "arma",
    "name": "Poniard",
    "gold": 25,
    "ev": 1,
    "obs": "",
    "effect": "dano 1d4+1",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-223-20260103155224",
    "type": "arma",
    "name": "Porrete",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "dano 1d3",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-224-20260103155224",
    "type": "arma",
    "name": "Punhal",
    "gold": 3,
    "ev": 1,
    "obs": "",
    "effect": "dano 1d4+1",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-225-20260103155224",
    "type": "arma",
    "name": "Punho",
    "gold": 0,
    "ev": null,
    "obs": "",
    "effect": "dano 1d2",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-226-20260103155224",
    "type": "arma",
    "name": "Punhos de bronze",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "dano 1d3",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-227-20260103155224",
    "type": "provisoes",
    "name": "Queijo, peça",
    "gold": 0,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-228-20260103155224",
    "type": "transporte",
    "name": "Ração (por dia)",
    "gold": 0.05,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-229-20260103155224",
    "type": "provisoes",
    "name": "Rações (1 dia)",
    "gold": 0.5,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-230-20260103155224",
    "type": "provisoes",
    "name": "Rações (1 semana)",
    "gold": 3,
    "ev": 4,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-231-20260103155224",
    "type": "arma",
    "name": "Ranseur",
    "gold": 8,
    "ev": 5,
    "obs": "2 mãos, haste",
    "effect": "dano 2d4",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-232-20260103155224",
    "type": "provisoes",
    "name": "Refeição de taberna, boa",
    "gold": 1,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-233-20260103155224",
    "type": "provisoes",
    "name": "Refeição de taberna, comum",
    "gold": 0.2,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-234-20260103155224",
    "type": "provisoes",
    "name": "Refeição leve (peixe, pães, frutas, queijo)",
    "gold": 0.1,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-235-20260103155224",
    "type": "provisoes",
    "name": "Refeição pesada (carnes, vegetais, pães, manteiga)",
    "gold": 0.3,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-236-20260103155224",
    "type": "roupas",
    "name": "Roupas de inverno, conjunto",
    "gold": 5,
    "ev": 4,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-237-20260103155224",
    "type": "arma",
    "name": "Sabre",
    "gold": 8,
    "ev": 2,
    "obs": "",
    "effect": "dano 1d6",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-238-20260103155224",
    "type": "roupas",
    "name": "Saia",
    "gold": 0.4,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-239-20260103155224",
    "type": "alojamento",
    "name": "Sala comunal (apenas o andar)",
    "gold": 0.01,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-240-20260103155224",
    "type": "roupas",
    "name": "Sapatos comuns",
    "gold": 0.2,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-241-20260103155224",
    "type": "transporte",
    "name": "Sela",
    "gold": 20,
    "ev": 5,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-242-20260103155224",
    "type": "arma",
    "name": "Sodegarami",
    "gold": 17,
    "ev": 5,
    "obs": "desarmar +3, haste",
    "effect": "dano 1d10",
    "proficience": [],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-243-20260103155224",
    "type": "alojamento",
    "name": "Suíte mobiliada",
    "gold": 50,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-244-20260103155224",
    "type": "alojamento",
    "name": "Suíte sem mobília",
    "gold": 25,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "tavern",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-245-20260103155224",
    "type": "provisoes",
    "name": "Tabaco (meio quilo)",
    "gold": 0,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-246-20260103155224",
    "type": "transporte",
    "name": "Trenó",
    "gold": 20,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "wheel",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-247-20260103155224",
    "type": "arma",
    "name": "Tridente",
    "gold": 10,
    "ev": 5,
    "obs": "projetil, haste",
    "effect": "dano 1d8 /3m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "dagger",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-248-20260103155224",
    "type": "roupas",
    "name": "Túnica",
    "gold": 0.3,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-249-20260103155224",
    "type": "roupas",
    "name": "Túnica longa",
    "gold": 1,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-250-20260103155224",
    "type": "roupas",
    "name": "Vestido",
    "gold": 1,
    "ev": 4,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-251-20260103155224",
    "type": "roupas",
    "name": "Vestido de Serviço",
    "gold": 0.5,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "hood",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-252-20260103155224",
    "type": "provisoes",
    "name": "Vinho comum (garrafa)",
    "gold": 0.2,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-253-20260103155224",
    "type": "provisoes",
    "name": "Vinho fino (garrafa)",
    "gold": 10,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-254-20260103155224",
    "type": "provisoes",
    "name": "Vinho branco Kathy",
    "gold": 1,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-255-20260103155224",
    "type": "provisoes",
    "name": "Vinho vermelho/branco (garrafa)",
    "gold": 5,
    "ev": null,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "food",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-256-20260103155224",
    "type": "municao",
    "name": "Virotes (12)",
    "gold": 1,
    "ev": 1,
    "obs": "besta",
    "effect": "",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "explorador",
      "paladino"
    ],
    "icon": "arrows",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-257-20260103155224",
    "type": "distancia",
    "name": "Zarabatana",
    "gold": 1,
    "ev": 3,
    "obs": "",
    "effect": "dano 1 /3m",
    "proficience": [
      "assassino",
      "bárbaro",
      "combatente",
      "druid",
      "explorador",
      "paladino"
    ],
    "icon": "bow",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1000-20260103155224",
    "type": "equipamento",
    "name": "Barril grande",
    "gold": 4,
    "ev": 9,
    "obs": "capacidade 9",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1001-20260103155224",
    "type": "equipamento",
    "name": "Barril pequeno",
    "gold": 2,
    "ev": 6,
    "obs": "capacidade 6",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1002-20260103155224",
    "type": "equipamento",
    "name": "Baú de viagem",
    "gold": 2,
    "ev": 3,
    "obs": "capacidade 5",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1003-20260103155224",
    "type": "equipamento",
    "name": "Baú grande",
    "gold": 5,
    "ev": 12,
    "obs": "capacidade 8",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1004-20260103155224",
    "type": "equipamento",
    "name": "Baú pequeno",
    "gold": 2,
    "ev": 4,
    "obs": "capacidade 6",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1005-20260103155224",
    "type": "equipamento",
    "name": "Bolinhas (saco c/ 25)",
    "gold": 1,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1006-20260103155224",
    "type": "equipamento",
    "name": "Cinto para componentes",
    "gold": 10,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1007-20260103155224",
    "type": "equipamento",
    "name": "Bolsa de cinto grande",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1008-20260103155224",
    "type": "equipamento",
    "name": "Bolsa de cinto pequena",
    "gold": 0.5,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1009-20260103155224",
    "type": "equipamento",
    "name": "Cabaça",
    "gold": 0.3,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1010-20260103155224",
    "type": "equipamento",
    "name": "Cachimbo",
    "gold": 5,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1011-20260103155224",
    "type": "equipamento",
    "name": "Cadeado e chave",
    "gold": 25,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1012-20260103155224",
    "type": "equipamento",
    "name": "Caixa de fogo (10 usos)",
    "gold": 1,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1013-20260103155224",
    "type": "equipamento",
    "name": "Caixão",
    "gold": 2,
    "ev": 4,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1014-20260103155224",
    "type": "equipamento",
    "name": "Cajado (3m)",
    "gold": 0.2,
    "ev": 5,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1015-20260103155224",
    "type": "equipamento",
    "name": "Caneca",
    "gold": 0.02,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1016-20260103155224",
    "type": "equipamento",
    "name": "Cantil (1,5L)",
    "gold": 1,
    "ev": 3,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1017-20260103155224",
    "type": "equipamento",
    "name": "Cavadeira",
    "gold": 1,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1018-20260103155224",
    "type": "equipamento",
    "name": "Cera de lacrar",
    "gold": 1,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1019-20260103155224",
    "type": "equipamento",
    "name": "Cesto",
    "gold": 0.4,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1020-20260103155224",
    "type": "equipamento",
    "name": "Chaleira, ferro",
    "gold": 1,
    "ev": 3,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1021-20260103155224",
    "type": "equipamento",
    "name": "Cítara",
    "gold": 40,
    "ev": 3,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1022-20260103155224",
    "type": "equipamento",
    "name": "Cobertor, inverno",
    "gold": 0.5,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1023-20260103155224",
    "type": "equipamento",
    "name": "Conjunto de costura (agulha, linha, etc)",
    "gold": 0.5,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1024-20260103155224",
    "type": "equipamento",
    "name": "Corda (20m)",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1025-20260103155224",
    "type": "equipamento",
    "name": "Corda de cânhamo (15m)",
    "gold": 1,
    "ev": 3,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1026-20260103155224",
    "type": "equipamento",
    "name": "Corda de ceda (15m)",
    "gold": 10,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1027-20260103155224",
    "type": "equipamento",
    "name": "Cordão (45m)",
    "gold": 0.4,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1028-20260103155224",
    "type": "equipamento",
    "name": "Corneta",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1029-20260103155224",
    "type": "equipamento",
    "name": "Corrente (6m)",
    "gold": 2,
    "ev": 12,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1030-20260103155224",
    "type": "equipamento",
    "name": "Cunha, divisão",
    "gold": 0.02,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1031-20260103155224",
    "type": "equipamento",
    "name": "equipamento de pesca (anzol, linha, etc)",
    "gold": 0.5,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1032-20260103155224",
    "type": "equipamento",
    "name": "Espelho pequeno de aço",
    "gold": 10,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1033-20260103155224",
    "type": "equipamento",
    "name": "Estacas/gancho (5)",
    "gold": 0.5,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1034-20260103155224",
    "type": "equipamento",
    "name": "Estojo para mapas/pergaminho",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1035-20260103155224",
    "type": "equipamento",
    "name": "Farol",
    "gold": 12,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1036-20260103155224",
    "type": "equipamento",
    "name": "Ferramentas de chaveiro",
    "gold": 30,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1037-20260103155224",
    "type": "equipamento",
    "name": "Flauta",
    "gold": 15,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1038-20260103155224",
    "type": "equipamento",
    "name": "Flautas de pã",
    "gold": 11,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1039-20260103155224",
    "type": "equipamento",
    "name": "Formão",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1040-20260103155224",
    "type": "equipamento",
    "name": "Frasco (30ml)",
    "gold": 0.03,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1041-20260103155224",
    "type": "equipamento",
    "name": "Gaita de fole",
    "gold": 0.1,
    "ev": 4,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1042-20260103155224",
    "type": "equipamento",
    "name": "Gancho de escalada",
    "gold": 35,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1043-20260103155224",
    "type": "equipamento",
    "name": "Gancho, ferro",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1044-20260103155224",
    "type": "equipamento",
    "name": "Garrafa",
    "gold": 2,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1045-20260103155224",
    "type": "equipamento",
    "name": "Giz (unidade)",
    "gold": 0.01,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1046-20260103155224",
    "type": "equipamento",
    "name": "Gongo",
    "gold": 18,
    "ev": 3,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1047-20260103155224",
    "type": "equipamento",
    "name": "Pote de gracha (meio quilo)",
    "gold": 0.02,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1048-20260103155224",
    "type": "equipamento",
    "name": "Harpa",
    "gold": 35,
    "ev": 4,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1049-20260103155224",
    "type": "equipamento",
    "name": "Incenso, vareta",
    "gold": 1,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1050-20260103155224",
    "type": "equipamento",
    "name": "Lâmpada aberta",
    "gold": 3,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1051-20260103155224",
    "type": "equipamento",
    "name": "Lanterna corta luz",
    "gold": 7,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1052-20260103155224",
    "type": "equipamento",
    "name": "Lenha (1 dia)",
    "gold": 0.01,
    "ev": 8,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1053-20260103155224",
    "type": "equipamento",
    "name": "Lima",
    "gold": 2,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1054-20260103155224",
    "type": "equipamento",
    "name": "Lima estreita, metal",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1055-20260103155224",
    "type": "equipamento",
    "name": "Lima larga, metal",
    "gold": 2,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1056-20260103155224",
    "type": "equipamento",
    "name": "Magnetita",
    "gold": 25,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1057-20260103155224",
    "type": "equipamento",
    "name": "Marreta",
    "gold": 6,
    "ev": 4,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1058-20260103155224",
    "type": "equipamento",
    "name": "Martelo",
    "gold": 1,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1059-20260103155224",
    "type": "equipamento",
    "name": "meias de lã",
    "gold": 0.1,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1060-20260103155224",
    "type": "equipamento",
    "name": "Mochila",
    "gold": 2,
    "ev": 2,
    "obs": "capacidade 8",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1061-20260103155224",
    "type": "equipamento",
    "name": "Mochila de ombro",
    "gold": 2,
    "ev": 3,
    "obs": "capacidade 10",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1062-20260103155224",
    "type": "equipamento",
    "name": "Navalha",
    "gold": 0.5,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1063-20260103155224",
    "type": "equipamento",
    "name": "Óleo p/ armadura e arma",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1064-20260103155224",
    "type": "equipamento",
    "name": "òleo, frasco",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1065-20260103155224",
    "type": "equipamento",
    "name": "Pá",
    "gold": 2,
    "ev": 3,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1066-20260103155224",
    "type": "equipamento",
    "name": "Panela",
    "gold": 3,
    "ev": 4,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1067-20260103155224",
    "type": "equipamento",
    "name": "Papel (10 folhas)",
    "gold": 10,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1068-20260103155224",
    "type": "equipamento",
    "name": "Pé de cabra",
    "gold": 2,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1069-20260103155224",
    "type": "equipamento",
    "name": "Pederneira e isqueiro",
    "gold": 1,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1070-20260103155224",
    "type": "equipamento",
    "name": "Pedra de esmeril",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1071-20260103155224",
    "type": "equipamento",
    "name": "Pena de escrever",
    "gold": 0.1,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1072-20260103155224",
    "type": "equipamento",
    "name": "Pergaminho (10 folhas)",
    "gold": 5,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1073-20260103155224",
    "type": "equipamento",
    "name": "Picareta, de minerador",
    "gold": 3,
    "ev": 4,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1074-20260103155224",
    "type": "equipamento",
    "name": "Pilão e almofariz",
    "gold": 3,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1075-20260103155224",
    "type": "equipamento",
    "name": "Pregos, ferro (50)",
    "gold": 0.5,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1076-20260103155224",
    "type": "equipamento",
    "name": "Punção",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1077-20260103155224",
    "type": "equipamento",
    "name": "Rede de dormir",
    "gold": 8,
    "ev": 4,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1078-20260103155224",
    "type": "equipamento",
    "name": "Rosário",
    "gold": 2,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1079-20260103155224",
    "type": "equipamento",
    "name": "Sabão, bara",
    "gold": 0.5,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1080-20260103155224",
    "type": "equipamento",
    "name": "Saco de dormir",
    "gold": 0.1,
    "ev": 3,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1081-20260103155224",
    "type": "equipamento",
    "name": "Saco de pó de giz",
    "gold": 0,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1082-20260103155224",
    "type": "equipamento",
    "name": "Saco grande",
    "gold": 0.5,
    "ev": 2,
    "obs": "capacidade 10",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1083-20260103155224",
    "type": "equipamento",
    "name": "Saco pequeno",
    "gold": 0.1,
    "ev": 1,
    "obs": "capacidade 6",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1084-20260103155224",
    "type": "equipamento",
    "name": "Serra de metal",
    "gold": 5,
    "ev": 2,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1085-20260103155224",
    "type": "equipamento",
    "name": "Símbolo sagrado, madeira",
    "gold": 1,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1086-20260103155224",
    "type": "equipamento",
    "name": "Símbolo sagrado, prata",
    "gold": 25,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1087-20260103155224",
    "type": "equipamento",
    "name": "Tambor",
    "gold": 9,
    "ev": 5,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1088-20260103155224",
    "type": "equipamento",
    "name": "Tenazes",
    "gold": 0.6,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1089-20260103155224",
    "type": "equipamento",
    "name": "Tenda, grande",
    "gold": 45,
    "ev": 10,
    "obs": "5 pessoas",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1090-20260103155224",
    "type": "equipamento",
    "name": "Tenda, média",
    "gold": 25,
    "ev": 7,
    "obs": "3 pessoas",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1091-20260103155224",
    "type": "equipamento",
    "name": "Tinta",
    "gold": 8,
    "ev": 0,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1092-20260103155224",
    "type": "equipamento",
    "name": "Tocha",
    "gold": 0.01,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1093-20260103155224",
    "type": "equipamento",
    "name": "Vassoura",
    "gold": 0.05,
    "ev": 3,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1094-20260103155224",
    "type": "equipamento",
    "name": "Vela (5)",
    "gold": 0.05,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1095-20260103155224",
    "type": "equipamento",
    "name": "Velino (10 folhas)",
    "gold": 15,
    "ev": 1,
    "obs": "",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  },
  {
    "id": "ID-1096-20260103155224",
    "type": "equipamento",
    "name": "Tenda, pequena",
    "gold": 10,
    "ev": 4,
    "obs": "1 pessoa",
    "effect": "",
    "proficience": [],
    "icon": "torch",
    "tags": "undefined",
    "image": "undefined"
  }
]